// Code generated by protoc-gen-go. DO NOT EDIT.
// source: orderer/rbft/cluster.proto

package rbft

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	common "github.com/hyperledger/fabric-protos-go/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TxType int32

const (
	TxType_TYPENORMAL TxType = 0
	TxType_TYPECONFIG TxType = 1
)

var TxType_name = map[int32]string{
	0: "TYPENORMAL",
	1: "TYPECONFIG",
}

var TxType_value = map[string]int32{
	"TYPENORMAL": 0,
	"TYPECONFIG": 1,
}

func (x TxType) String() string {
	return proto.EnumName(TxType_name, int32(x))
}

func (TxType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_eed053c395633f6a, []int{0}
}

type ConfChangeType int32

const (
	ConfChangeType_ConfChangeAddNode        ConfChangeType = 0
	ConfChangeType_ConfChangeRemoveNode     ConfChangeType = 1
	ConfChangeType_ConfChangeUpdateNode     ConfChangeType = 2
	ConfChangeType_ConfChangeAddLearnerNode ConfChangeType = 3
)

var ConfChangeType_name = map[int32]string{
	0: "ConfChangeAddNode",
	1: "ConfChangeRemoveNode",
	2: "ConfChangeUpdateNode",
	3: "ConfChangeAddLearnerNode",
}

var ConfChangeType_value = map[string]int32{
	"ConfChangeAddNode":        0,
	"ConfChangeRemoveNode":     1,
	"ConfChangeUpdateNode":     2,
	"ConfChangeAddLearnerNode": 3,
}

func (x ConfChangeType) String() string {
	return proto.EnumName(ConfChangeType_name, int32(x))
}

func (ConfChangeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_eed053c395633f6a, []int{1}
}

// StepRequest wraps a message that is sent to a cluster member.
type StepRequest struct {
	// Types that are valid to be assigned to Payload:
	//	*StepRequest_RequestRequest
	//	*StepRequest_BlockRequest
	//	*StepRequest_ComMsgRequest
	//	*StepRequest_CommitMsgRequest
	//	*StepRequest_LastBlockRequest
	//	*StepRequest_PrepareMsgRequest
	//	*StepRequest_ProposalMsgRequest
	Payload              isStepRequest_Payload `protobuf_oneof:"payload"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *StepRequest) Reset()         { *m = StepRequest{} }
func (m *StepRequest) String() string { return proto.CompactTextString(m) }
func (*StepRequest) ProtoMessage()    {}
func (*StepRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eed053c395633f6a, []int{0}
}

func (m *StepRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StepRequest.Unmarshal(m, b)
}
func (m *StepRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StepRequest.Marshal(b, m, deterministic)
}
func (m *StepRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StepRequest.Merge(m, src)
}
func (m *StepRequest) XXX_Size() int {
	return xxx_messageInfo_StepRequest.Size(m)
}
func (m *StepRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StepRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StepRequest proto.InternalMessageInfo

type isStepRequest_Payload interface {
	isStepRequest_Payload()
}

type StepRequest_RequestRequest struct {
	RequestRequest *Request `protobuf:"bytes,1,opt,name=request_request,json=requestRequest,proto3,oneof"`
}

type StepRequest_BlockRequest struct {
	BlockRequest *Block `protobuf:"bytes,2,opt,name=block_request,json=blockRequest,proto3,oneof"`
}

type StepRequest_ComMsgRequest struct {
	ComMsgRequest *ComMsg `protobuf:"bytes,3,opt,name=com_msg_request,json=comMsgRequest,proto3,oneof"`
}

type StepRequest_CommitMsgRequest struct {
	CommitMsgRequest *CommitMsg `protobuf:"bytes,4,opt,name=commit_msg_request,json=commitMsgRequest,proto3,oneof"`
}

type StepRequest_LastBlockRequest struct {
	LastBlockRequest *LastBlock `protobuf:"bytes,5,opt,name=last_block_request,json=lastBlockRequest,proto3,oneof"`
}

type StepRequest_PrepareMsgRequest struct {
	PrepareMsgRequest *PrepareMsg `protobuf:"bytes,6,opt,name=prepare_msg_request,json=prepareMsgRequest,proto3,oneof"`
}

type StepRequest_ProposalMsgRequest struct {
	ProposalMsgRequest *ProposalMsg `protobuf:"bytes,7,opt,name=proposal_msg_request,json=proposalMsgRequest,proto3,oneof"`
}

func (*StepRequest_RequestRequest) isStepRequest_Payload() {}

func (*StepRequest_BlockRequest) isStepRequest_Payload() {}

func (*StepRequest_ComMsgRequest) isStepRequest_Payload() {}

func (*StepRequest_CommitMsgRequest) isStepRequest_Payload() {}

func (*StepRequest_LastBlockRequest) isStepRequest_Payload() {}

func (*StepRequest_PrepareMsgRequest) isStepRequest_Payload() {}

func (*StepRequest_ProposalMsgRequest) isStepRequest_Payload() {}

func (m *StepRequest) GetPayload() isStepRequest_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *StepRequest) GetRequestRequest() *Request {
	if x, ok := m.GetPayload().(*StepRequest_RequestRequest); ok {
		return x.RequestRequest
	}
	return nil
}

func (m *StepRequest) GetBlockRequest() *Block {
	if x, ok := m.GetPayload().(*StepRequest_BlockRequest); ok {
		return x.BlockRequest
	}
	return nil
}

func (m *StepRequest) GetComMsgRequest() *ComMsg {
	if x, ok := m.GetPayload().(*StepRequest_ComMsgRequest); ok {
		return x.ComMsgRequest
	}
	return nil
}

func (m *StepRequest) GetCommitMsgRequest() *CommitMsg {
	if x, ok := m.GetPayload().(*StepRequest_CommitMsgRequest); ok {
		return x.CommitMsgRequest
	}
	return nil
}

func (m *StepRequest) GetLastBlockRequest() *LastBlock {
	if x, ok := m.GetPayload().(*StepRequest_LastBlockRequest); ok {
		return x.LastBlockRequest
	}
	return nil
}

func (m *StepRequest) GetPrepareMsgRequest() *PrepareMsg {
	if x, ok := m.GetPayload().(*StepRequest_PrepareMsgRequest); ok {
		return x.PrepareMsgRequest
	}
	return nil
}

func (m *StepRequest) GetProposalMsgRequest() *ProposalMsg {
	if x, ok := m.GetPayload().(*StepRequest_ProposalMsgRequest); ok {
		return x.ProposalMsgRequest
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*StepRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*StepRequest_RequestRequest)(nil),
		(*StepRequest_BlockRequest)(nil),
		(*StepRequest_ComMsgRequest)(nil),
		(*StepRequest_CommitMsgRequest)(nil),
		(*StepRequest_LastBlockRequest)(nil),
		(*StepRequest_PrepareMsgRequest)(nil),
		(*StepRequest_ProposalMsgRequest)(nil),
	}
}

// StepResponse is a message received from a cluster member.
type StepResponse struct {
	// Types that are valid to be assigned to Payload:
	//	*StepResponse_RequestRes
	Payload              isStepResponse_Payload `protobuf_oneof:"payload"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *StepResponse) Reset()         { *m = StepResponse{} }
func (m *StepResponse) String() string { return proto.CompactTextString(m) }
func (*StepResponse) ProtoMessage()    {}
func (*StepResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eed053c395633f6a, []int{1}
}

func (m *StepResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StepResponse.Unmarshal(m, b)
}
func (m *StepResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StepResponse.Marshal(b, m, deterministic)
}
func (m *StepResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StepResponse.Merge(m, src)
}
func (m *StepResponse) XXX_Size() int {
	return xxx_messageInfo_StepResponse.Size(m)
}
func (m *StepResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StepResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StepResponse proto.InternalMessageInfo

type isStepResponse_Payload interface {
	isStepResponse_Payload()
}

type StepResponse_RequestRes struct {
	RequestRes *Response `protobuf:"bytes,1,opt,name=request_res,json=requestRes,proto3,oneof"`
}

func (*StepResponse_RequestRes) isStepResponse_Payload() {}

func (m *StepResponse) GetPayload() isStepResponse_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *StepResponse) GetRequestRes() *Response {
	if x, ok := m.GetPayload().(*StepResponse_RequestRes); ok {
		return x.RequestRes
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*StepResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*StepResponse_RequestRes)(nil),
	}
}

// Operation 请求的具体操作
type Operation struct {
	Envelope             *common.Envelope `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	ChannelId            string           `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	ConfigSeq            uint64           `protobuf:"varint,3,opt,name=config_seq,json=configSeq,proto3" json:"config_seq,omitempty"`
	Type                 string           `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Operation) Reset()         { *m = Operation{} }
func (m *Operation) String() string { return proto.CompactTextString(m) }
func (*Operation) ProtoMessage()    {}
func (*Operation) Descriptor() ([]byte, []int) {
	return fileDescriptor_eed053c395633f6a, []int{2}
}

func (m *Operation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Operation.Unmarshal(m, b)
}
func (m *Operation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Operation.Marshal(b, m, deterministic)
}
func (m *Operation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Operation.Merge(m, src)
}
func (m *Operation) XXX_Size() int {
	return xxx_messageInfo_Operation.Size(m)
}
func (m *Operation) XXX_DiscardUnknown() {
	xxx_messageInfo_Operation.DiscardUnknown(m)
}

var xxx_messageInfo_Operation proto.InternalMessageInfo

func (m *Operation) GetEnvelope() *common.Envelope {
	if m != nil {
		return m.Envelope
	}
	return nil
}

func (m *Operation) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

func (m *Operation) GetConfigSeq() uint64 {
	if m != nil {
		return m.ConfigSeq
	}
	return 0
}

func (m *Operation) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type Result struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_eed053c395633f6a, []int{3}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

// Request 客户端发起的请求
type Request struct {
	Op                   *Operation              `protobuf:"bytes,1,opt,name=op,proto3" json:"op,omitempty"`
	TimeStamp            uint64                  `protobuf:"varint,2,opt,name=time_stamp,json=timeStamp,proto3" json:"time_stamp,omitempty"`
	Id                   uint64                  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Signature            []byte                  `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	SignatureHeader      *common.SignatureHeader `protobuf:"bytes,5,opt,name=signature_header,json=signatureHeader,proto3" json:"signature_header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_eed053c395633f6a, []int{4}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetOp() *Operation {
	if m != nil {
		return m.Op
	}
	return nil
}

func (m *Request) GetTimeStamp() uint64 {
	if m != nil {
		return m.TimeStamp
	}
	return 0
}

func (m *Request) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Request) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *Request) GetSignatureHeader() *common.SignatureHeader {
	if m != nil {
		return m.SignatureHeader
	}
	return nil
}

type Message struct {
	Requests             []*Request `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_eed053c395633f6a, []int{5}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetRequests() []*Request {
	if m != nil {
		return m.Requests
	}
	return nil
}

type Block struct {
	Message              *Message                `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	TimeStamp            uint64                  `protobuf:"varint,2,opt,name=time_stamp,json=timeStamp,proto3" json:"time_stamp,omitempty"`
	Signature            []byte                  `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	ChannelId            string                  `protobuf:"bytes,4,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	SignatureHeader      *common.SignatureHeader `protobuf:"bytes,5,opt,name=signature_header,json=signatureHeader,proto3" json:"signature_header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_eed053c395633f6a, []int{6}
}

func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (m *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(m, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetMessage() *Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *Block) GetTimeStamp() uint64 {
	if m != nil {
		return m.TimeStamp
	}
	return 0
}

func (m *Block) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *Block) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

func (m *Block) GetSignatureHeader() *common.SignatureHeader {
	if m != nil {
		return m.SignatureHeader
	}
	return nil
}

type ComMsg struct {
	View                 uint64                  `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	Identify             uint64                  `protobuf:"varint,2,opt,name=identify,proto3" json:"identify,omitempty"`
	Com                  []byte                  `protobuf:"bytes,3,opt,name=com,proto3" json:"com,omitempty"`
	ACom                 []byte                  `protobuf:"bytes,4,opt,name=a_com,json=aCom,proto3" json:"a_com,omitempty"`
	Signature            []byte                  `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	ChannelId            string                  `protobuf:"bytes,6,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	SignatureHeader      *common.SignatureHeader `protobuf:"bytes,7,opt,name=signature_header,json=signatureHeader,proto3" json:"signature_header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ComMsg) Reset()         { *m = ComMsg{} }
func (m *ComMsg) String() string { return proto.CompactTextString(m) }
func (*ComMsg) ProtoMessage()    {}
func (*ComMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_eed053c395633f6a, []int{7}
}

func (m *ComMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComMsg.Unmarshal(m, b)
}
func (m *ComMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComMsg.Marshal(b, m, deterministic)
}
func (m *ComMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComMsg.Merge(m, src)
}
func (m *ComMsg) XXX_Size() int {
	return xxx_messageInfo_ComMsg.Size(m)
}
func (m *ComMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ComMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ComMsg proto.InternalMessageInfo

func (m *ComMsg) GetView() uint64 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *ComMsg) GetIdentify() uint64 {
	if m != nil {
		return m.Identify
	}
	return 0
}

func (m *ComMsg) GetCom() []byte {
	if m != nil {
		return m.Com
	}
	return nil
}

func (m *ComMsg) GetACom() []byte {
	if m != nil {
		return m.ACom
	}
	return nil
}

func (m *ComMsg) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *ComMsg) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

func (m *ComMsg) GetSignatureHeader() *common.SignatureHeader {
	if m != nil {
		return m.SignatureHeader
	}
	return nil
}

type CommitMsg struct {
	View                 uint64                  `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	Sequence             int64                   `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Digest               string                  `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	Threshold            []byte                  `protobuf:"bytes,4,opt,name=threshold,proto3" json:"threshold,omitempty"`
	Signature            []byte                  `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	ChannelId            string                  `protobuf:"bytes,6,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	SignatureHeader      *common.SignatureHeader `protobuf:"bytes,7,opt,name=signature_header,json=signatureHeader,proto3" json:"signature_header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *CommitMsg) Reset()         { *m = CommitMsg{} }
func (m *CommitMsg) String() string { return proto.CompactTextString(m) }
func (*CommitMsg) ProtoMessage()    {}
func (*CommitMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_eed053c395633f6a, []int{8}
}

func (m *CommitMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitMsg.Unmarshal(m, b)
}
func (m *CommitMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitMsg.Marshal(b, m, deterministic)
}
func (m *CommitMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitMsg.Merge(m, src)
}
func (m *CommitMsg) XXX_Size() int {
	return xxx_messageInfo_CommitMsg.Size(m)
}
func (m *CommitMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitMsg.DiscardUnknown(m)
}

var xxx_messageInfo_CommitMsg proto.InternalMessageInfo

func (m *CommitMsg) GetView() uint64 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *CommitMsg) GetSequence() int64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *CommitMsg) GetDigest() string {
	if m != nil {
		return m.Digest
	}
	return ""
}

func (m *CommitMsg) GetThreshold() []byte {
	if m != nil {
		return m.Threshold
	}
	return nil
}

func (m *CommitMsg) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *CommitMsg) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

func (m *CommitMsg) GetSignatureHeader() *common.SignatureHeader {
	if m != nil {
		return m.SignatureHeader
	}
	return nil
}

type LastBlock struct {
	Coms                 map[string]uint64 `protobuf:"bytes,1,rep,name=coms,proto3" json:"coms,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	AComs                map[string]uint64 `protobuf:"bytes,2,rep,name=a_coms,json=aComs,proto3" json:"a_coms,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *LastBlock) Reset()         { *m = LastBlock{} }
func (m *LastBlock) String() string { return proto.CompactTextString(m) }
func (*LastBlock) ProtoMessage()    {}
func (*LastBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_eed053c395633f6a, []int{9}
}

func (m *LastBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LastBlock.Unmarshal(m, b)
}
func (m *LastBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LastBlock.Marshal(b, m, deterministic)
}
func (m *LastBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LastBlock.Merge(m, src)
}
func (m *LastBlock) XXX_Size() int {
	return xxx_messageInfo_LastBlock.Size(m)
}
func (m *LastBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_LastBlock.DiscardUnknown(m)
}

var xxx_messageInfo_LastBlock proto.InternalMessageInfo

func (m *LastBlock) GetComs() map[string]uint64 {
	if m != nil {
		return m.Coms
	}
	return nil
}

func (m *LastBlock) GetAComs() map[string]uint64 {
	if m != nil {
		return m.AComs
	}
	return nil
}

type PrepareMsg struct {
	View                 int64                   `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	Sequence             string                  `protobuf:"bytes,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Digest               string                  `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	PartSig              []byte                  `protobuf:"bytes,4,opt,name=part_sig,json=partSig,proto3" json:"part_sig,omitempty"`
	Signature            []byte                  `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	ChannelId            string                  `protobuf:"bytes,6,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	SignatureHeader      *common.SignatureHeader `protobuf:"bytes,7,opt,name=signature_header,json=signatureHeader,proto3" json:"signature_header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *PrepareMsg) Reset()         { *m = PrepareMsg{} }
func (m *PrepareMsg) String() string { return proto.CompactTextString(m) }
func (*PrepareMsg) ProtoMessage()    {}
func (*PrepareMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_eed053c395633f6a, []int{10}
}

func (m *PrepareMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrepareMsg.Unmarshal(m, b)
}
func (m *PrepareMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrepareMsg.Marshal(b, m, deterministic)
}
func (m *PrepareMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrepareMsg.Merge(m, src)
}
func (m *PrepareMsg) XXX_Size() int {
	return xxx_messageInfo_PrepareMsg.Size(m)
}
func (m *PrepareMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_PrepareMsg.DiscardUnknown(m)
}

var xxx_messageInfo_PrepareMsg proto.InternalMessageInfo

func (m *PrepareMsg) GetView() int64 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *PrepareMsg) GetSequence() string {
	if m != nil {
		return m.Sequence
	}
	return ""
}

func (m *PrepareMsg) GetDigest() string {
	if m != nil {
		return m.Digest
	}
	return ""
}

func (m *PrepareMsg) GetPartSig() []byte {
	if m != nil {
		return m.PartSig
	}
	return nil
}

func (m *PrepareMsg) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *PrepareMsg) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

func (m *PrepareMsg) GetSignatureHeader() *common.SignatureHeader {
	if m != nil {
		return m.SignatureHeader
	}
	return nil
}

type ProposalMsg struct {
	Cp                   []byte                  `protobuf:"bytes,1,opt,name=cp,proto3" json:"cp,omitempty"`
	View                 uint64                  `protobuf:"varint,2,opt,name=view,proto3" json:"view,omitempty"`
	Sequence             uint64                  `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Digest               string                  `protobuf:"bytes,4,opt,name=digest,proto3" json:"digest,omitempty"`
	BlockType            bool                    `protobuf:"varint,5,opt,name=block_type,json=blockType,proto3" json:"block_type,omitempty"`
	Payload              []byte                  `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature            []byte                  `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`
	ChannelId            string                  `protobuf:"bytes,8,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	SignatureHeader      *common.SignatureHeader `protobuf:"bytes,9,opt,name=signature_header,json=signatureHeader,proto3" json:"signature_header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ProposalMsg) Reset()         { *m = ProposalMsg{} }
func (m *ProposalMsg) String() string { return proto.CompactTextString(m) }
func (*ProposalMsg) ProtoMessage()    {}
func (*ProposalMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_eed053c395633f6a, []int{11}
}

func (m *ProposalMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProposalMsg.Unmarshal(m, b)
}
func (m *ProposalMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProposalMsg.Marshal(b, m, deterministic)
}
func (m *ProposalMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProposalMsg.Merge(m, src)
}
func (m *ProposalMsg) XXX_Size() int {
	return xxx_messageInfo_ProposalMsg.Size(m)
}
func (m *ProposalMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ProposalMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ProposalMsg proto.InternalMessageInfo

func (m *ProposalMsg) GetCp() []byte {
	if m != nil {
		return m.Cp
	}
	return nil
}

func (m *ProposalMsg) GetView() uint64 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *ProposalMsg) GetSequence() uint64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *ProposalMsg) GetDigest() string {
	if m != nil {
		return m.Digest
	}
	return ""
}

func (m *ProposalMsg) GetBlockType() bool {
	if m != nil {
		return m.BlockType
	}
	return false
}

func (m *ProposalMsg) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *ProposalMsg) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *ProposalMsg) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

func (m *ProposalMsg) GetSignatureHeader() *common.SignatureHeader {
	if m != nil {
		return m.SignatureHeader
	}
	return nil
}

// Response returns a success
// or failure status to the sender.
type Response struct {
	Channel string `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	// Status code, which may be used to programatically respond to success/failure.
	Status common.Status `protobuf:"varint,2,opt,name=status,proto3,enum=common.Status" json:"status,omitempty"`
	// Info string which may contain additional information about the returned status.
	Info                 string   `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_eed053c395633f6a, []int{12}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *Response) GetStatus() common.Status {
	if m != nil {
		return m.Status
	}
	return common.Status_UNKNOWN
}

func (m *Response) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

type ConfChange struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 int32    `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	NodeId               uint64   `protobuf:"varint,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Context              []byte   `protobuf:"bytes,4,opt,name=context,proto3" json:"context,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfChange) Reset()         { *m = ConfChange{} }
func (m *ConfChange) String() string { return proto.CompactTextString(m) }
func (*ConfChange) ProtoMessage()    {}
func (*ConfChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_eed053c395633f6a, []int{13}
}

func (m *ConfChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfChange.Unmarshal(m, b)
}
func (m *ConfChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfChange.Marshal(b, m, deterministic)
}
func (m *ConfChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfChange.Merge(m, src)
}
func (m *ConfChange) XXX_Size() int {
	return xxx_messageInfo_ConfChange.Size(m)
}
func (m *ConfChange) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfChange.DiscardUnknown(m)
}

var xxx_messageInfo_ConfChange proto.InternalMessageInfo

func (m *ConfChange) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ConfChange) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *ConfChange) GetNodeId() uint64 {
	if m != nil {
		return m.NodeId
	}
	return 0
}

func (m *ConfChange) GetContext() []byte {
	if m != nil {
		return m.Context
	}
	return nil
}

func init() {
	proto.RegisterEnum("rbft.TxType", TxType_name, TxType_value)
	proto.RegisterEnum("rbft.ConfChangeType", ConfChangeType_name, ConfChangeType_value)
	proto.RegisterType((*StepRequest)(nil), "rbft.StepRequest")
	proto.RegisterType((*StepResponse)(nil), "rbft.StepResponse")
	proto.RegisterType((*Operation)(nil), "rbft.Operation")
	proto.RegisterType((*Result)(nil), "rbft.Result")
	proto.RegisterType((*Request)(nil), "rbft.Request")
	proto.RegisterType((*Message)(nil), "rbft.Message")
	proto.RegisterType((*Block)(nil), "rbft.Block")
	proto.RegisterType((*ComMsg)(nil), "rbft.ComMsg")
	proto.RegisterType((*CommitMsg)(nil), "rbft.CommitMsg")
	proto.RegisterType((*LastBlock)(nil), "rbft.LastBlock")
	proto.RegisterMapType((map[string]uint64)(nil), "rbft.LastBlock.AComsEntry")
	proto.RegisterMapType((map[string]uint64)(nil), "rbft.LastBlock.ComsEntry")
	proto.RegisterType((*PrepareMsg)(nil), "rbft.PrepareMsg")
	proto.RegisterType((*ProposalMsg)(nil), "rbft.ProposalMsg")
	proto.RegisterType((*Response)(nil), "rbft.Response")
	proto.RegisterType((*ConfChange)(nil), "rbft.ConfChange")
}

func init() { proto.RegisterFile("orderer/rbft/cluster.proto", fileDescriptor_eed053c395633f6a) }

var fileDescriptor_eed053c395633f6a = []byte{
	// 1109 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x56, 0xdd, 0x6e, 0xe3, 0x44,
	0x14, 0x8e, 0x13, 0x27, 0x8e, 0x4f, 0xdb, 0x34, 0x9d, 0x16, 0x36, 0x1b, 0xed, 0x0a, 0x94, 0x0b,
	0x28, 0x15, 0x4d, 0x68, 0x59, 0x41, 0x85, 0x90, 0x50, 0x1b, 0x15, 0x5a, 0xa9, 0x3f, 0xab, 0x69,
	0xb9, 0x80, 0x9b, 0xe0, 0xd8, 0x13, 0xc7, 0x5a, 0xdb, 0xe3, 0xce, 0x4c, 0xca, 0xe6, 0x19, 0x78,
	0x08, 0x1e, 0x84, 0x47, 0xe0, 0x86, 0x47, 0xd8, 0x47, 0x40, 0x3c, 0x01, 0x9a, 0x1f, 0x3b, 0x71,
	0xa1, 0x4b, 0x17, 0xad, 0xb4, 0x57, 0x99, 0x73, 0xce, 0x7c, 0x5f, 0xce, 0x39, 0xdf, 0xf1, 0xcc,
	0x40, 0x97, 0xb2, 0x80, 0x30, 0xc2, 0x06, 0x6c, 0x3c, 0x11, 0x03, 0x3f, 0x9e, 0x71, 0x41, 0x58,
	0x3f, 0x63, 0x54, 0x50, 0x64, 0x4b, 0x5f, 0x77, 0xd3, 0xa7, 0x49, 0x42, 0xd3, 0x81, 0xfe, 0xd1,
	0xa1, 0xde, 0xef, 0x35, 0x58, 0xb9, 0x12, 0x24, 0xc3, 0xe4, 0x66, 0x46, 0xb8, 0x40, 0x07, 0xb0,
	0xce, 0xf4, 0x72, 0x64, 0x7e, 0x3b, 0xd6, 0x87, 0xd6, 0xf6, 0xca, 0xfe, 0x5a, 0x5f, 0x92, 0xf4,
	0xcd, 0xbe, 0x93, 0x0a, 0x6e, 0x99, 0x78, 0x8e, 0xdc, 0x87, 0xb5, 0x71, 0x4c, 0xfd, 0x17, 0x05,
	0xae, 0xaa, 0x70, 0x2b, 0x1a, 0x77, 0x24, 0x43, 0x27, 0x15, 0xbc, 0xaa, 0xf6, 0xe4, 0x98, 0x2f,
	0x60, 0xdd, 0xa7, 0xc9, 0x28, 0xe1, 0x61, 0x81, 0xaa, 0x29, 0xd4, 0xaa, 0x46, 0x0d, 0x69, 0x72,
	0xce, 0xc3, 0x93, 0x0a, 0x5e, 0xf3, 0xd5, 0x2a, 0xc7, 0x7d, 0x03, 0x48, 0x56, 0x11, 0x89, 0x12,
	0xd4, 0x56, 0xd0, 0xf5, 0x02, 0x9a, 0x44, 0x42, 0xa3, 0xdb, 0x7e, 0x6e, 0x2c, 0x11, 0xc4, 0x1e,
	0x17, 0xa3, 0x72, 0xc6, 0xf5, 0x65, 0x82, 0x33, 0x8f, 0x8b, 0x3c, 0xeb, 0x76, 0x9c, 0x1b, 0x39,
	0xc1, 0x11, 0x6c, 0x66, 0x8c, 0x64, 0x1e, 0x23, 0xa5, 0x14, 0x1a, 0x8a, 0xa1, 0xad, 0x19, 0x9e,
	0xeb, 0x0d, 0x3a, 0x87, 0x8d, 0xac, 0xb0, 0x72, 0x8e, 0x63, 0xd8, 0xca, 0x18, 0xcd, 0x28, 0xf7,
	0xe2, 0x12, 0x89, 0xa3, 0x48, 0x36, 0x72, 0x12, 0xbd, 0x43, 0xb3, 0xa0, 0x6c, 0x61, 0x1a, 0x9a,
	0x23, 0x17, 0x9c, 0xcc, 0x9b, 0xc7, 0xd4, 0x0b, 0x7a, 0x67, 0xb0, 0xaa, 0xc5, 0xe4, 0x19, 0x4d,
	0x39, 0x41, 0x7b, 0xb0, 0xb2, 0x50, 0x93, 0x1b, 0x25, 0x5b, 0xb9, 0x92, 0x7a, 0xd3, 0x49, 0x05,
	0x43, 0x21, 0x25, 0x5f, 0x66, 0xfb, 0xc5, 0x02, 0xf7, 0x32, 0x23, 0xcc, 0x13, 0x11, 0x4d, 0xd1,
	0xa7, 0xd0, 0x24, 0xe9, 0x2d, 0x89, 0x69, 0x46, 0x0c, 0x51, 0xbb, 0x6f, 0x46, 0xe9, 0xd8, 0xf8,
	0x71, 0xb1, 0x03, 0x3d, 0x05, 0xf0, 0xa7, 0x5e, 0x9a, 0x92, 0x78, 0x14, 0x05, 0x6a, 0x14, 0x5c,
	0xec, 0x1a, 0xcf, 0x69, 0xa0, 0xc2, 0x34, 0x9d, 0x44, 0xe1, 0x88, 0x93, 0x1b, 0xa5, 0xb9, 0x8d,
	0x5d, 0xed, 0xb9, 0x22, 0x37, 0x08, 0x81, 0x2d, 0xe6, 0x19, 0x51, 0x8a, 0xba, 0x58, 0xad, 0x7b,
	0x4d, 0x68, 0x60, 0xc2, 0x67, 0xb1, 0xe8, 0xfd, 0x66, 0x81, 0x93, 0xf7, 0xf0, 0x03, 0xa8, 0xd2,
	0xcc, 0xe4, 0x63, 0x84, 0x2b, 0x52, 0xc6, 0x55, 0x9a, 0xc9, 0x7f, 0x12, 0x51, 0x42, 0x46, 0x5c,
	0x78, 0x49, 0xa6, 0x12, 0xb1, 0xb1, 0x2b, 0x3d, 0x57, 0xd2, 0x81, 0x5a, 0x50, 0x8d, 0x02, 0x93,
	0x40, 0x35, 0x0a, 0xd0, 0x13, 0x70, 0x79, 0x14, 0xa6, 0x9e, 0x98, 0x31, 0xfd, 0xf7, 0xab, 0x78,
	0xe1, 0x40, 0x47, 0xd0, 0x2e, 0x8c, 0xd1, 0x94, 0x78, 0x01, 0x61, 0x66, 0x68, 0x1e, 0xe5, 0xbd,
	0xb8, 0xca, 0xe3, 0x27, 0x2a, 0x8c, 0xd7, 0x79, 0xd9, 0xd1, 0x7b, 0x06, 0xce, 0x39, 0xe1, 0xdc,
	0x0b, 0x09, 0xfa, 0x04, 0x9a, 0xa6, 0xf3, 0x52, 0x9b, 0xda, 0x3f, 0xbe, 0x32, 0x5c, 0x84, 0x7b,
	0x7f, 0x58, 0x50, 0x57, 0x03, 0x88, 0x3e, 0x06, 0x27, 0xd1, 0xf8, 0xf2, 0x97, 0x69, 0x48, 0x71,
	0x1e, 0xfd, 0xaf, 0xca, 0x4b, 0x95, 0xd6, 0xee, 0x56, 0x5a, 0xd6, 0xcf, 0xbe, 0xab, 0xdf, 0xdb,
	0x68, 0xc4, 0x2b, 0x0b, 0x1a, 0xfa, 0x03, 0x97, 0x7a, 0xdf, 0x46, 0xe4, 0x67, 0x55, 0x90, 0x8d,
	0xd5, 0x1a, 0x75, 0xa1, 0x19, 0x05, 0x24, 0x15, 0xd1, 0x64, 0x6e, 0x92, 0x2f, 0x6c, 0xd4, 0x86,
	0x9a, 0x4f, 0x13, 0x93, 0xb5, 0x5c, 0xa2, 0x4d, 0xa8, 0x7b, 0x23, 0xe9, 0xd3, 0x9a, 0xd9, 0xde,
	0x90, 0x26, 0xe5, 0x12, 0xeb, 0xaf, 0x2f, 0xb1, 0xf1, 0x90, 0x12, 0x9d, 0x37, 0x2c, 0xf1, 0x2f,
	0x0b, 0xdc, 0xe2, 0x20, 0xba, 0xaf, 0x4a, 0x2e, 0x35, 0x4e, 0x7d, 0xa2, 0xaa, 0xac, 0xe1, 0xc2,
	0x46, 0xef, 0x43, 0x23, 0x88, 0xc2, 0xfc, 0x50, 0x74, 0xb1, 0xb1, 0x64, 0x59, 0x62, 0xca, 0x08,
	0x9f, 0xd2, 0x38, 0xc8, 0x67, 0xb4, 0x70, 0xbc, 0xfb, 0xa2, 0x5f, 0x59, 0xe0, 0x16, 0x87, 0x27,
	0xda, 0x05, 0xdb, 0xa7, 0x49, 0x3e, 0xdf, 0x8f, 0xef, 0x9c, 0xad, 0xf2, 0x98, 0xe6, 0xc7, 0xa9,
	0x60, 0x73, 0xac, 0xb6, 0xa1, 0x3d, 0x68, 0x28, 0x1d, 0x79, 0xa7, 0xaa, 0x00, 0xdd, 0xbb, 0x80,
	0xc3, 0x05, 0xa2, 0x2e, 0x45, 0xe6, 0xdd, 0x2f, 0x55, 0x8f, 0xb5, 0x4f, 0x4e, 0xc6, 0x0b, 0x32,
	0x57, 0x2d, 0x76, 0xb1, 0x5c, 0xa2, 0x2d, 0xa8, 0xdf, 0x7a, 0xf1, 0x8c, 0x98, 0x21, 0xd2, 0xc6,
	0x57, 0xd5, 0x03, 0xab, 0x7b, 0x00, 0x70, 0xf8, 0xbf, 0x90, 0xbd, 0x3f, 0x2d, 0x80, 0xc5, 0xe9,
	0x5e, 0x12, 0xb6, 0x76, 0x8f, 0xb0, 0xee, 0x03, 0x84, 0x7d, 0x0c, 0xcd, 0xcc, 0x63, 0x62, 0xc4,
	0xa3, 0xd0, 0xe8, 0xea, 0x48, 0xfb, 0x2a, 0x0a, 0xdf, 0xbd, 0xaa, 0xbf, 0x56, 0x61, 0x65, 0xe9,
	0x2e, 0x92, 0x07, 0xa7, 0xaf, 0x0f, 0xde, 0x55, 0x5c, 0xf5, 0xb3, 0xa2, 0x07, 0xd5, 0x7b, 0x86,
	0x5b, 0x1f, 0xb1, 0xff, 0xd6, 0x03, 0xbb, 0xd4, 0x83, 0xa7, 0x00, 0xfa, 0x52, 0x56, 0x17, 0x80,
	0xac, 0xb4, 0x89, 0x5d, 0xe5, 0xb9, 0x9e, 0x67, 0x04, 0x75, 0x8a, 0xeb, 0x49, 0x95, 0xa9, 0x3a,
	0xa4, 0xcc, 0x72, 0x87, 0x9c, 0xd7, 0x77, 0xa8, 0xf9, 0x90, 0x0e, 0xb9, 0x6f, 0xd8, 0xa1, 0x9f,
	0xa0, 0x59, 0x5c, 0xbc, 0x1d, 0x70, 0x0c, 0xb9, 0x19, 0xa8, 0xdc, 0x44, 0x1f, 0x41, 0x83, 0x0b,
	0x4f, 0xcc, 0xb8, 0xea, 0x54, 0x6b, 0xbf, 0x55, 0xf0, 0x2b, 0x2f, 0x36, 0x51, 0xd9, 0xcf, 0x28,
	0x9d, 0x50, 0x33, 0x21, 0x6a, 0xdd, 0xf3, 0x01, 0x86, 0x34, 0x9d, 0x0c, 0xa7, 0x5e, 0x1a, 0x12,
	0x73, 0x75, 0x59, 0xc5, 0xd5, 0x95, 0x5f, 0x9a, 0x92, 0xb7, 0xae, 0x2f, 0x4d, 0xf4, 0x08, 0x9c,
	0x94, 0x06, 0x64, 0x54, 0xdc, 0x71, 0x0d, 0x69, 0x9e, 0x06, 0x2a, 0x41, 0x9a, 0x0a, 0xf2, 0x52,
	0xe4, 0x93, 0x66, 0xcc, 0x9d, 0x6d, 0x68, 0x5c, 0xbf, 0x54, 0xbd, 0x6e, 0x01, 0x5c, 0xff, 0xf0,
	0xfc, 0xf8, 0xe2, 0x12, 0x9f, 0x1f, 0x9e, 0xb5, 0x2b, 0xb9, 0x3d, 0xbc, 0xbc, 0xf8, 0xf6, 0xf4,
	0xbb, 0xb6, 0xb5, 0x33, 0x87, 0xd6, 0x22, 0x1d, 0x85, 0x78, 0x0f, 0x36, 0x16, 0x9e, 0xc3, 0x20,
	0xb8, 0xa0, 0x01, 0x69, 0x57, 0x50, 0x07, 0xb6, 0x16, 0x6e, 0x4c, 0x12, 0x7a, 0x4b, 0x54, 0xc4,
	0x2a, 0x47, 0xbe, 0xcf, 0x02, 0x4f, 0xe8, 0x48, 0x15, 0x3d, 0x81, 0x4e, 0x89, 0xea, 0x8c, 0x78,
	0x2c, 0x25, 0x4c, 0x45, 0x6b, 0xfb, 0x5f, 0x83, 0x33, 0xd4, 0x4f, 0x5c, 0xb4, 0x07, 0xb6, 0x7c,
	0xf3, 0x20, 0xf3, 0x5e, 0x5a, 0x7a, 0xcc, 0x76, 0xd1, 0xb2, 0x4b, 0x2b, 0xb3, 0x6d, 0x7d, 0x66,
	0x1d, 0x8d, 0x61, 0x87, 0xb2, 0xb0, 0x3f, 0x9d, 0x67, 0x84, 0xc5, 0x24, 0x08, 0x09, 0xeb, 0x4f,
	0xbc, 0x31, 0x8b, 0x7c, 0xfd, 0x28, 0xe6, 0x7d, 0xf3, 0x96, 0x56, 0xf0, 0x1f, 0x9f, 0x85, 0x91,
	0x98, 0xce, 0xc6, 0x52, 0xa7, 0xc1, 0x12, 0x64, 0xa0, 0x21, 0xbb, 0x1a, 0xb2, 0x1b, 0xd2, 0xc1,
	0xf2, 0x0b, 0x7c, 0xdc, 0x50, 0xfe, 0xcf, 0xff, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xcc, 0x6d, 0x34,
	0x1b, 0x98, 0x0b, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ClusterClient is the client API for Cluster service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ClusterClient interface {
	// Step passes an implementation-specific message to another cluster member.
	Step(ctx context.Context, opts ...grpc.CallOption) (Cluster_StepClient, error)
}

type clusterClient struct {
	cc *grpc.ClientConn
}

func NewClusterClient(cc *grpc.ClientConn) ClusterClient {
	return &clusterClient{cc}
}

func (c *clusterClient) Step(ctx context.Context, opts ...grpc.CallOption) (Cluster_StepClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Cluster_serviceDesc.Streams[0], "/rbft.Cluster/Step", opts...)
	if err != nil {
		return nil, err
	}
	x := &clusterStepClient{stream}
	return x, nil
}

type Cluster_StepClient interface {
	Send(*StepRequest) error
	Recv() (*StepResponse, error)
	grpc.ClientStream
}

type clusterStepClient struct {
	grpc.ClientStream
}

func (x *clusterStepClient) Send(m *StepRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *clusterStepClient) Recv() (*StepResponse, error) {
	m := new(StepResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ClusterServer is the server API for Cluster service.
type ClusterServer interface {
	// Step passes an implementation-specific message to another cluster member.
	Step(Cluster_StepServer) error
}

// UnimplementedClusterServer can be embedded to have forward compatible implementations.
type UnimplementedClusterServer struct {
}

func (*UnimplementedClusterServer) Step(srv Cluster_StepServer) error {
	return status.Errorf(codes.Unimplemented, "method Step not implemented")
}

func RegisterClusterServer(s *grpc.Server, srv ClusterServer) {
	s.RegisterService(&_Cluster_serviceDesc, srv)
}

func _Cluster_Step_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ClusterServer).Step(&clusterStepServer{stream})
}

type Cluster_StepServer interface {
	Send(*StepResponse) error
	Recv() (*StepRequest, error)
	grpc.ServerStream
}

type clusterStepServer struct {
	grpc.ServerStream
}

func (x *clusterStepServer) Send(m *StepResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *clusterStepServer) Recv() (*StepRequest, error) {
	m := new(StepRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Cluster_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rbft.Cluster",
	HandlerType: (*ClusterServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Step",
			Handler:       _Cluster_Step_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "orderer/rbft/cluster.proto",
}
