// Code generated by protoc-gen-go. DO NOT EDIT.
// source: orderer/rbft/configuration.proto

package rbft

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// ConfigMetadata is serialized and set as the value of ConsensusType.Metadata in
// a channel configuration when the ConsensusType.Type is set "rbft".
type ConfigMetadata struct {
	Consenters           []*Consenter `protobuf:"bytes,1,rep,name=consenters,proto3" json:"consenters,omitempty"`
	Options              *Options     `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ConfigMetadata) Reset()         { *m = ConfigMetadata{} }
func (m *ConfigMetadata) String() string { return proto.CompactTextString(m) }
func (*ConfigMetadata) ProtoMessage()    {}
func (*ConfigMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f671607bbbbefb2, []int{0}
}

func (m *ConfigMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigMetadata.Unmarshal(m, b)
}
func (m *ConfigMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigMetadata.Marshal(b, m, deterministic)
}
func (m *ConfigMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigMetadata.Merge(m, src)
}
func (m *ConfigMetadata) XXX_Size() int {
	return xxx_messageInfo_ConfigMetadata.Size(m)
}
func (m *ConfigMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigMetadata proto.InternalMessageInfo

func (m *ConfigMetadata) GetConsenters() []*Consenter {
	if m != nil {
		return m.Consenters
	}
	return nil
}

func (m *ConfigMetadata) GetOptions() *Options {
	if m != nil {
		return m.Options
	}
	return nil
}

// Consenter represents a consenting node (i.e. replica).
type Consenter struct {
	Host                 string   `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port                 uint32   `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	ClientTlsCert        []byte   `protobuf:"bytes,3,opt,name=client_tls_cert,json=clientTlsCert,proto3" json:"client_tls_cert,omitempty"`
	ServerTlsCert        []byte   `protobuf:"bytes,4,opt,name=server_tls_cert,json=serverTlsCert,proto3" json:"server_tls_cert,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Consenter) Reset()         { *m = Consenter{} }
func (m *Consenter) String() string { return proto.CompactTextString(m) }
func (*Consenter) ProtoMessage()    {}
func (*Consenter) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f671607bbbbefb2, []int{1}
}

func (m *Consenter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Consenter.Unmarshal(m, b)
}
func (m *Consenter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Consenter.Marshal(b, m, deterministic)
}
func (m *Consenter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Consenter.Merge(m, src)
}
func (m *Consenter) XXX_Size() int {
	return xxx_messageInfo_Consenter.Size(m)
}
func (m *Consenter) XXX_DiscardUnknown() {
	xxx_messageInfo_Consenter.DiscardUnknown(m)
}

var xxx_messageInfo_Consenter proto.InternalMessageInfo

func (m *Consenter) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Consenter) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Consenter) GetClientTlsCert() []byte {
	if m != nil {
		return m.ClientTlsCert
	}
	return nil
}

func (m *Consenter) GetServerTlsCert() []byte {
	if m != nil {
		return m.ServerTlsCert
	}
	return nil
}

// Options to be specified for all the rbft nodes. These can be modified on a
// per-channel basis.
type Options struct {
	ExecuteMaxNum     uint32 `protobuf:"varint,1,opt,name=execute_max_num,json=executeMaxNum,proto3" json:"execute_max_num,omitempty"`
	K                 int64  `protobuf:"varint,2,opt,name=k,proto3" json:"k,omitempty"`
	WaterL            int64  `protobuf:"varint,3,opt,name=water_l,json=waterL,proto3" json:"water_l,omitempty"`
	LogMultiplier     int64  `protobuf:"varint,4,opt,name=Log_multiplier,json=LogMultiplier,proto3" json:"Log_multiplier,omitempty"`
	View              uint64 `protobuf:"varint,5,opt,name=view,proto3" json:"view,omitempty"`
	TickInterval      string `protobuf:"bytes,6,opt,name=tick_interval,json=tickInterval,proto3" json:"tick_interval,omitempty"`
	MaxInflightBlocks uint32 `protobuf:"varint,7,opt,name=max_inflight_blocks,json=maxInflightBlocks,proto3" json:"max_inflight_blocks,omitempty"`
	// Take snapshot when cumulative data exceeds certain size in bytes.
	SnapshotIntervalSize uint32   `protobuf:"varint,8,opt,name=snapshot_interval_size,json=snapshotIntervalSize,proto3" json:"snapshot_interval_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Options) Reset()         { *m = Options{} }
func (m *Options) String() string { return proto.CompactTextString(m) }
func (*Options) ProtoMessage()    {}
func (*Options) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f671607bbbbefb2, []int{2}
}

func (m *Options) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Options.Unmarshal(m, b)
}
func (m *Options) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Options.Marshal(b, m, deterministic)
}
func (m *Options) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Options.Merge(m, src)
}
func (m *Options) XXX_Size() int {
	return xxx_messageInfo_Options.Size(m)
}
func (m *Options) XXX_DiscardUnknown() {
	xxx_messageInfo_Options.DiscardUnknown(m)
}

var xxx_messageInfo_Options proto.InternalMessageInfo

func (m *Options) GetExecuteMaxNum() uint32 {
	if m != nil {
		return m.ExecuteMaxNum
	}
	return 0
}

func (m *Options) GetK() int64 {
	if m != nil {
		return m.K
	}
	return 0
}

func (m *Options) GetWaterL() int64 {
	if m != nil {
		return m.WaterL
	}
	return 0
}

func (m *Options) GetLogMultiplier() int64 {
	if m != nil {
		return m.LogMultiplier
	}
	return 0
}

func (m *Options) GetView() uint64 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *Options) GetTickInterval() string {
	if m != nil {
		return m.TickInterval
	}
	return ""
}

func (m *Options) GetMaxInflightBlocks() uint32 {
	if m != nil {
		return m.MaxInflightBlocks
	}
	return 0
}

func (m *Options) GetSnapshotIntervalSize() uint32 {
	if m != nil {
		return m.SnapshotIntervalSize
	}
	return 0
}

func init() {
	proto.RegisterType((*ConfigMetadata)(nil), "rbft.ConfigMetadata")
	proto.RegisterType((*Consenter)(nil), "rbft.Consenter")
	proto.RegisterType((*Options)(nil), "rbft.Options")
}

func init() { proto.RegisterFile("orderer/rbft/configuration.proto", fileDescriptor_6f671607bbbbefb2) }

var fileDescriptor_6f671607bbbbefb2 = []byte{
	// 439 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x92, 0x51, 0x6f, 0xd3, 0x30,
	0x14, 0x85, 0x95, 0xa5, 0xb4, 0xcc, 0x6b, 0x36, 0x61, 0x10, 0xe4, 0x31, 0x2a, 0x02, 0x22, 0xa4,
	0x25, 0xd2, 0xd8, 0x2f, 0x58, 0x9f, 0x26, 0xb5, 0x20, 0x19, 0x9e, 0x78, 0x89, 0x9c, 0xf4, 0x36,
	0x31, 0x75, 0xe2, 0xc8, 0xbe, 0xe9, 0xca, 0x5e, 0xf9, 0x1f, 0xfc, 0x56, 0x64, 0x3b, 0x2d, 0x7d,
	0x73, 0xbe, 0x73, 0xce, 0xcd, 0x89, 0x73, 0x49, 0xa2, 0xf4, 0x06, 0x34, 0xe8, 0x5c, 0x97, 0x5b,
	0xcc, 0x2b, 0xd5, 0x6d, 0x45, 0x3d, 0x68, 0x8e, 0x42, 0x75, 0x59, 0xaf, 0x15, 0x2a, 0x3a, 0xb1,
	0xca, 0xe2, 0x17, 0xb9, 0x5e, 0x3a, 0x71, 0x0d, 0xc8, 0x37, 0x1c, 0x39, 0xcd, 0x09, 0xa9, 0x54,
	0x67, 0xa0, 0x43, 0xd0, 0x26, 0x0e, 0x92, 0x30, 0xbd, 0xba, 0xbb, 0xc9, 0xac, 0x39, 0x5b, 0x1e,
	0x39, 0x3b, 0xb3, 0xd0, 0x4f, 0x64, 0xa6, 0x7a, 0x3b, 0xd8, 0xc4, 0x17, 0x49, 0x90, 0x5e, 0xdd,
	0x45, 0xde, 0xfd, 0xcd, 0x43, 0x76, 0x54, 0x17, 0x7f, 0x02, 0x72, 0x79, 0x1a, 0x41, 0x29, 0x99,
	0x34, 0xca, 0x60, 0x1c, 0x24, 0x41, 0x7a, 0xc9, 0xdc, 0xd9, 0xb2, 0x5e, 0x69, 0x74, 0x73, 0x22,
	0xe6, 0xce, 0xf4, 0x23, 0xb9, 0xa9, 0xa4, 0x80, 0x0e, 0x0b, 0x94, 0xa6, 0xa8, 0x40, 0x63, 0x1c,
	0x26, 0x41, 0x3a, 0x67, 0x91, 0xc7, 0x3f, 0xa4, 0x59, 0x82, 0xf7, 0x19, 0xd0, 0x7b, 0xd0, 0xff,
	0x7d, 0x13, 0xef, 0xf3, 0x78, 0xf4, 0x2d, 0xfe, 0x5e, 0x90, 0xd9, 0x58, 0xcd, 0x66, 0xe0, 0x00,
	0xd5, 0x80, 0x50, 0xb4, 0xfc, 0x50, 0x74, 0x43, 0xeb, 0xea, 0x44, 0x2c, 0x1a, 0xf1, 0x9a, 0x1f,
	0xbe, 0x0e, 0x2d, 0x9d, 0x93, 0x60, 0xe7, 0x4a, 0x85, 0x2c, 0xd8, 0xd1, 0x77, 0x64, 0xf6, 0xc4,
	0x11, 0x74, 0x21, 0x5d, 0x93, 0x90, 0x4d, 0xdd, 0xe3, 0x8a, 0x7e, 0x20, 0xd7, 0x2b, 0x55, 0x17,
	0xed, 0x20, 0x51, 0xf4, 0x52, 0x80, 0x76, 0x0d, 0x42, 0x16, 0xad, 0x54, 0xbd, 0x3e, 0x41, 0xfb,
	0x95, 0x7b, 0x01, 0x4f, 0xf1, 0x8b, 0x24, 0x48, 0x27, 0xcc, 0x9d, 0xe9, 0x7b, 0x12, 0xa1, 0xa8,
	0x76, 0x85, 0xb0, 0x77, 0xb3, 0xe7, 0x32, 0x9e, 0xba, 0x6b, 0x99, 0x5b, 0xf8, 0x38, 0x32, 0x9a,
	0x91, 0xd7, 0xb6, 0xa6, 0xe8, 0xb6, 0x52, 0xd4, 0x0d, 0x16, 0xa5, 0x54, 0xd5, 0xce, 0xc4, 0x33,
	0x57, 0xf9, 0x55, 0xcb, 0x0f, 0x8f, 0xa3, 0xf2, 0xe0, 0x04, 0x7a, 0x4f, 0xde, 0x9a, 0x8e, 0xf7,
	0xa6, 0x51, 0x78, 0x1a, 0x5c, 0x18, 0xf1, 0x0c, 0xf1, 0x4b, 0x17, 0x79, 0x73, 0x54, 0x8f, 0x6f,
	0xf8, 0x2e, 0x9e, 0xe1, 0xa1, 0x24, 0x9f, 0x95, 0xae, 0xb3, 0xe6, 0x77, 0x0f, 0x5a, 0xc2, 0xa6,
	0x06, 0x9d, 0x6d, 0x79, 0xa9, 0x45, 0xe5, 0x17, 0xc7, 0x64, 0xe3, 0x6a, 0xb9, 0xbf, 0xfc, 0xf3,
	0xbe, 0x16, 0xd8, 0x0c, 0x65, 0x56, 0xa9, 0x36, 0x3f, 0x8b, 0xe4, 0x3e, 0x72, 0xeb, 0x23, 0xb7,
	0xb5, 0xca, 0xcf, 0x17, 0xb2, 0x9c, 0x3a, 0xfe, 0xe5, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x83,
	0x49, 0xa9, 0x31, 0xa7, 0x02, 0x00, 0x00,
}
