// Code generated by protoc-gen-go. DO NOT EDIT.
// source: orderer/rbft/metadata.proto

package rbft

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// BlockMetadata stores data used by the rbft OSNs when
// coordinating with each other, to be serialized into
// block meta dta field and used after failres and restarts.
type BlockMetadata struct {
	// Maintains a mapping between the cluster's OSNs
	// and their Raft IDs.
	ConsenterIds []uint64 `protobuf:"varint,1,rep,packed,name=consenter_ids,json=consenterIds,proto3" json:"consenter_ids,omitempty"`
	// Carries the rbft ID value that will be assigned
	// to the next OSN that will join this cluster.
	NextConsenterId uint64 `protobuf:"varint,2,opt,name=next_consenter_id,json=nextConsenterId,proto3" json:"next_consenter_id,omitempty"`
	// view of rbft entry for current block.
	RbftView             uint64   `protobuf:"varint,3,opt,name=rbft_view,json=rbftView,proto3" json:"rbft_view,omitempty"`
	RbftSequence         int64    `protobuf:"varint,4,opt,name=rbft_sequence,json=rbftSequence,proto3" json:"rbft_sequence,omitempty"`
	RbftCheckpoint       int64    `protobuf:"varint,5,opt,name=rbft_checkpoint,json=rbftCheckpoint,proto3" json:"rbft_checkpoint,omitempty"`
	RbftWaterL           int64    `protobuf:"varint,6,opt,name=rbft_waterL,json=rbftWaterL,proto3" json:"rbft_waterL,omitempty"`
	RbftTotalTxNum       uint64   `protobuf:"varint,7,opt,name=rbft_total_tx_num,json=rbftTotalTxNum,proto3" json:"rbft_total_tx_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockMetadata) Reset()         { *m = BlockMetadata{} }
func (m *BlockMetadata) String() string { return proto.CompactTextString(m) }
func (*BlockMetadata) ProtoMessage()    {}
func (*BlockMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_00d00953b7466f35, []int{0}
}

func (m *BlockMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockMetadata.Unmarshal(m, b)
}
func (m *BlockMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockMetadata.Marshal(b, m, deterministic)
}
func (m *BlockMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockMetadata.Merge(m, src)
}
func (m *BlockMetadata) XXX_Size() int {
	return xxx_messageInfo_BlockMetadata.Size(m)
}
func (m *BlockMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_BlockMetadata proto.InternalMessageInfo

func (m *BlockMetadata) GetConsenterIds() []uint64 {
	if m != nil {
		return m.ConsenterIds
	}
	return nil
}

func (m *BlockMetadata) GetNextConsenterId() uint64 {
	if m != nil {
		return m.NextConsenterId
	}
	return 0
}

func (m *BlockMetadata) GetRbftView() uint64 {
	if m != nil {
		return m.RbftView
	}
	return 0
}

func (m *BlockMetadata) GetRbftSequence() int64 {
	if m != nil {
		return m.RbftSequence
	}
	return 0
}

func (m *BlockMetadata) GetRbftCheckpoint() int64 {
	if m != nil {
		return m.RbftCheckpoint
	}
	return 0
}

func (m *BlockMetadata) GetRbftWaterL() int64 {
	if m != nil {
		return m.RbftWaterL
	}
	return 0
}

func (m *BlockMetadata) GetRbftTotalTxNum() uint64 {
	if m != nil {
		return m.RbftTotalTxNum
	}
	return 0
}

// ClusterMetadata encapsulates metadata that is exchanged among cluster nodes
type ClusterMetadata struct {
	// Indicates active nodes in cluster that are reacheable by rbft leader
	ActiveNodes          []uint64 `protobuf:"varint,1,rep,packed,name=active_nodes,json=activeNodes,proto3" json:"active_nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClusterMetadata) Reset()         { *m = ClusterMetadata{} }
func (m *ClusterMetadata) String() string { return proto.CompactTextString(m) }
func (*ClusterMetadata) ProtoMessage()    {}
func (*ClusterMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_00d00953b7466f35, []int{1}
}

func (m *ClusterMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterMetadata.Unmarshal(m, b)
}
func (m *ClusterMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterMetadata.Marshal(b, m, deterministic)
}
func (m *ClusterMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterMetadata.Merge(m, src)
}
func (m *ClusterMetadata) XXX_Size() int {
	return xxx_messageInfo_ClusterMetadata.Size(m)
}
func (m *ClusterMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterMetadata proto.InternalMessageInfo

func (m *ClusterMetadata) GetActiveNodes() []uint64 {
	if m != nil {
		return m.ActiveNodes
	}
	return nil
}

func init() {
	proto.RegisterType((*BlockMetadata)(nil), "rbft.BlockMetadata")
	proto.RegisterType((*ClusterMetadata)(nil), "rbft.ClusterMetadata")
}

func init() { proto.RegisterFile("orderer/rbft/metadata.proto", fileDescriptor_00d00953b7466f35) }

var fileDescriptor_00d00953b7466f35 = []byte{
	// 325 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x91, 0x41, 0x4f, 0xc2, 0x30,
	0x14, 0xc7, 0x03, 0x4c, 0xd4, 0x02, 0x12, 0x7a, 0x6a, 0xc2, 0x41, 0xc4, 0x83, 0x48, 0xc2, 0x76,
	0x90, 0x4f, 0x00, 0x27, 0x13, 0xe5, 0x80, 0x44, 0x13, 0x2f, 0x4b, 0xd7, 0x3d, 0x46, 0xc3, 0xd6,
	0x62, 0xf7, 0x06, 0xf8, 0x49, 0xfc, 0xba, 0xa6, 0x1d, 0xe2, 0xae, 0xbf, 0xf7, 0x7b, 0xfd, 0x37,
	0xff, 0x47, 0xfa, 0xda, 0xc4, 0x60, 0xc0, 0x04, 0x26, 0x5a, 0x63, 0x90, 0x01, 0xf2, 0x98, 0x23,
	0xf7, 0x77, 0x46, 0xa3, 0xa6, 0x9e, 0x85, 0xc3, 0x9f, 0x3a, 0xe9, 0xcc, 0x52, 0x2d, 0xb6, 0xaf,
	0xa7, 0x29, 0xbd, 0x27, 0x1d, 0xa1, 0x55, 0x0e, 0x0a, 0xc1, 0x84, 0x32, 0xce, 0x59, 0x6d, 0xd0,
	0x18, 0x79, 0xcb, 0xf6, 0x19, 0x3e, 0xc7, 0x39, 0x1d, 0x93, 0x9e, 0x82, 0x23, 0x86, 0x55, 0x93,
	0xd5, 0x07, 0xb5, 0x91, 0xb7, 0xec, 0xda, 0xc1, 0xfc, 0x5f, 0xa6, 0x7d, 0x72, 0x6d, 0xa3, 0xc2,
	0xbd, 0x84, 0x03, 0x6b, 0x38, 0xe7, 0xca, 0x82, 0x77, 0x09, 0x07, 0x9b, 0xe6, 0x86, 0x39, 0x7c,
	0x15, 0xa0, 0x04, 0x30, 0x6f, 0x50, 0x1b, 0x35, 0x96, 0x6d, 0x0b, 0xdf, 0x4e, 0x8c, 0x3e, 0x90,
	0xae, 0x93, 0xc4, 0x06, 0xc4, 0x76, 0xa7, 0xa5, 0x42, 0x76, 0xe1, 0xb4, 0x1b, 0x8b, 0xe7, 0x67,
	0x4a, 0x6f, 0x49, 0xcb, 0x89, 0x07, 0x8e, 0x60, 0x5e, 0x58, 0xd3, 0x49, 0xc4, 0xa2, 0x0f, 0x47,
	0xe8, 0x23, 0xe9, 0x39, 0x01, 0x35, 0xf2, 0x34, 0xc4, 0x63, 0xa8, 0x8a, 0x8c, 0x5d, 0xba, 0x3f,
	0xb9, 0xb7, 0x56, 0x96, 0xaf, 0x8e, 0x8b, 0x22, 0x1b, 0x4e, 0x49, 0x77, 0x9e, 0x16, 0x39, 0x82,
	0x39, 0x57, 0x73, 0x47, 0xda, 0x5c, 0xa0, 0xdc, 0x43, 0xa8, 0x74, 0x0c, 0x7f, 0xcd, 0xb4, 0x4a,
	0xb6, 0xb0, 0x68, 0x16, 0x91, 0xb1, 0x36, 0x89, 0xbf, 0xf9, 0xde, 0x81, 0x49, 0x21, 0x4e, 0xc0,
	0xf8, 0x6b, 0x1e, 0x19, 0x29, 0xca, 0xd6, 0x73, 0xff, 0x74, 0x12, 0xdf, 0xa6, 0x7d, 0x4e, 0x13,
	0x89, 0x9b, 0x22, 0xf2, 0x85, 0xce, 0x82, 0xca, 0x4a, 0x50, 0xae, 0x4c, 0xca, 0x95, 0x49, 0xa2,
	0x83, 0xea, 0x21, 0xa3, 0xa6, 0xe3, 0x4f, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xf2, 0x71, 0x55,
	0x93, 0xdf, 0x01, 0x00, 0x00,
}
