// Code generated by protoc-gen-go. DO NOT EDIT.
// source: orderer/pbft/cluster.proto

package pbft

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	common "github.com/hyperledger/fabric-protos-go/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TxType int32

const (
	TxType_TYPENORMAL TxType = 0
	TxType_TYPECONFIG TxType = 1
)

var TxType_name = map[int32]string{
	0: "TYPENORMAL",
	1: "TYPECONFIG",
}

var TxType_value = map[string]int32{
	"TYPENORMAL": 0,
	"TYPECONFIG": 1,
}

func (x TxType) String() string {
	return proto.EnumName(TxType_name, int32(x))
}

func (TxType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1d2d862f434b808f, []int{0}
}

// StepRequest wraps a message that is sent to a cluster member.
type StepRequest struct {
	// Types that are valid to be assigned to Payload:
	//	*StepRequest_RequestRequest
	//	*StepRequest_PreprepareRequest
	//	*StepRequest_PrepareRequest
	//	*StepRequest_CommitRequest
	//	*StepRequest_CheckpointRequest
	Payload              isStepRequest_Payload `protobuf_oneof:"payload"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *StepRequest) Reset()         { *m = StepRequest{} }
func (m *StepRequest) String() string { return proto.CompactTextString(m) }
func (*StepRequest) ProtoMessage()    {}
func (*StepRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d2d862f434b808f, []int{0}
}

func (m *StepRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StepRequest.Unmarshal(m, b)
}
func (m *StepRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StepRequest.Marshal(b, m, deterministic)
}
func (m *StepRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StepRequest.Merge(m, src)
}
func (m *StepRequest) XXX_Size() int {
	return xxx_messageInfo_StepRequest.Size(m)
}
func (m *StepRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StepRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StepRequest proto.InternalMessageInfo

type isStepRequest_Payload interface {
	isStepRequest_Payload()
}

type StepRequest_RequestRequest struct {
	RequestRequest *Request `protobuf:"bytes,1,opt,name=request_request,json=requestRequest,proto3,oneof"`
}

type StepRequest_PreprepareRequest struct {
	PreprepareRequest *PrePrepare `protobuf:"bytes,2,opt,name=preprepare_request,json=preprepareRequest,proto3,oneof"`
}

type StepRequest_PrepareRequest struct {
	PrepareRequest *Prepare `protobuf:"bytes,3,opt,name=prepare_request,json=prepareRequest,proto3,oneof"`
}

type StepRequest_CommitRequest struct {
	CommitRequest *Commit `protobuf:"bytes,4,opt,name=commit_request,json=commitRequest,proto3,oneof"`
}

type StepRequest_CheckpointRequest struct {
	CheckpointRequest *CheckPoint `protobuf:"bytes,5,opt,name=checkpoint_request,json=checkpointRequest,proto3,oneof"`
}

func (*StepRequest_RequestRequest) isStepRequest_Payload() {}

func (*StepRequest_PreprepareRequest) isStepRequest_Payload() {}

func (*StepRequest_PrepareRequest) isStepRequest_Payload() {}

func (*StepRequest_CommitRequest) isStepRequest_Payload() {}

func (*StepRequest_CheckpointRequest) isStepRequest_Payload() {}

func (m *StepRequest) GetPayload() isStepRequest_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *StepRequest) GetRequestRequest() *Request {
	if x, ok := m.GetPayload().(*StepRequest_RequestRequest); ok {
		return x.RequestRequest
	}
	return nil
}

func (m *StepRequest) GetPreprepareRequest() *PrePrepare {
	if x, ok := m.GetPayload().(*StepRequest_PreprepareRequest); ok {
		return x.PreprepareRequest
	}
	return nil
}

func (m *StepRequest) GetPrepareRequest() *Prepare {
	if x, ok := m.GetPayload().(*StepRequest_PrepareRequest); ok {
		return x.PrepareRequest
	}
	return nil
}

func (m *StepRequest) GetCommitRequest() *Commit {
	if x, ok := m.GetPayload().(*StepRequest_CommitRequest); ok {
		return x.CommitRequest
	}
	return nil
}

func (m *StepRequest) GetCheckpointRequest() *CheckPoint {
	if x, ok := m.GetPayload().(*StepRequest_CheckpointRequest); ok {
		return x.CheckpointRequest
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*StepRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*StepRequest_RequestRequest)(nil),
		(*StepRequest_PreprepareRequest)(nil),
		(*StepRequest_PrepareRequest)(nil),
		(*StepRequest_CommitRequest)(nil),
		(*StepRequest_CheckpointRequest)(nil),
	}
}

// StepResponse is a message received from a cluster member.
type StepResponse struct {
	// Types that are valid to be assigned to Payload:
	//	*StepResponse_RequestRes
	Payload              isStepResponse_Payload `protobuf_oneof:"payload"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *StepResponse) Reset()         { *m = StepResponse{} }
func (m *StepResponse) String() string { return proto.CompactTextString(m) }
func (*StepResponse) ProtoMessage()    {}
func (*StepResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d2d862f434b808f, []int{1}
}

func (m *StepResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StepResponse.Unmarshal(m, b)
}
func (m *StepResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StepResponse.Marshal(b, m, deterministic)
}
func (m *StepResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StepResponse.Merge(m, src)
}
func (m *StepResponse) XXX_Size() int {
	return xxx_messageInfo_StepResponse.Size(m)
}
func (m *StepResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StepResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StepResponse proto.InternalMessageInfo

type isStepResponse_Payload interface {
	isStepResponse_Payload()
}

type StepResponse_RequestRes struct {
	RequestRes *Response `protobuf:"bytes,1,opt,name=request_res,json=requestRes,proto3,oneof"`
}

func (*StepResponse_RequestRes) isStepResponse_Payload() {}

func (m *StepResponse) GetPayload() isStepResponse_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *StepResponse) GetRequestRes() *Response {
	if x, ok := m.GetPayload().(*StepResponse_RequestRes); ok {
		return x.RequestRes
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*StepResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*StepResponse_RequestRes)(nil),
	}
}

// Operation 请求的具体操作
type Operation struct {
	Envelope             *common.Envelope `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	ChannelId            string           `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	ConfigSeq            uint64           `protobuf:"varint,3,opt,name=config_seq,json=configSeq,proto3" json:"config_seq,omitempty"`
	Type                 string           `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Operation) Reset()         { *m = Operation{} }
func (m *Operation) String() string { return proto.CompactTextString(m) }
func (*Operation) ProtoMessage()    {}
func (*Operation) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d2d862f434b808f, []int{2}
}

func (m *Operation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Operation.Unmarshal(m, b)
}
func (m *Operation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Operation.Marshal(b, m, deterministic)
}
func (m *Operation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Operation.Merge(m, src)
}
func (m *Operation) XXX_Size() int {
	return xxx_messageInfo_Operation.Size(m)
}
func (m *Operation) XXX_DiscardUnknown() {
	xxx_messageInfo_Operation.DiscardUnknown(m)
}

var xxx_messageInfo_Operation proto.InternalMessageInfo

func (m *Operation) GetEnvelope() *common.Envelope {
	if m != nil {
		return m.Envelope
	}
	return nil
}

func (m *Operation) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

func (m *Operation) GetConfigSeq() uint64 {
	if m != nil {
		return m.ConfigSeq
	}
	return 0
}

func (m *Operation) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type Result struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d2d862f434b808f, []int{3}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

// Request 客户端发起的请求
type Request struct {
	Op                   *Operation `protobuf:"bytes,1,opt,name=op,proto3" json:"op,omitempty"`
	TimeStamp            uint64     `protobuf:"varint,2,opt,name=time_stamp,json=timeStamp,proto3" json:"time_stamp,omitempty"`
	Id                   uint64     `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Signature            []byte     `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d2d862f434b808f, []int{4}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetOp() *Operation {
	if m != nil {
		return m.Op
	}
	return nil
}

func (m *Request) GetTimeStamp() uint64 {
	if m != nil {
		return m.TimeStamp
	}
	return 0
}

func (m *Request) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Request) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type Message struct {
	Requests             []*Request `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d2d862f434b808f, []int{5}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetRequests() []*Request {
	if m != nil {
		return m.Requests
	}
	return nil
}

// PrePrepare Pre-Prepare
type PrePrepare struct {
	View                 uint64   `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	Sequence             int64    `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Digest               string   `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	Message              *Message `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Identify             uint64   `protobuf:"varint,5,opt,name=identify,proto3" json:"identify,omitempty"`
	Signature            []byte   `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
	ChannelId            string   `protobuf:"bytes,7,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrePrepare) Reset()         { *m = PrePrepare{} }
func (m *PrePrepare) String() string { return proto.CompactTextString(m) }
func (*PrePrepare) ProtoMessage()    {}
func (*PrePrepare) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d2d862f434b808f, []int{6}
}

func (m *PrePrepare) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrePrepare.Unmarshal(m, b)
}
func (m *PrePrepare) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrePrepare.Marshal(b, m, deterministic)
}
func (m *PrePrepare) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrePrepare.Merge(m, src)
}
func (m *PrePrepare) XXX_Size() int {
	return xxx_messageInfo_PrePrepare.Size(m)
}
func (m *PrePrepare) XXX_DiscardUnknown() {
	xxx_messageInfo_PrePrepare.DiscardUnknown(m)
}

var xxx_messageInfo_PrePrepare proto.InternalMessageInfo

func (m *PrePrepare) GetView() uint64 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *PrePrepare) GetSequence() int64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *PrePrepare) GetDigest() string {
	if m != nil {
		return m.Digest
	}
	return ""
}

func (m *PrePrepare) GetMessage() *Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *PrePrepare) GetIdentify() uint64 {
	if m != nil {
		return m.Identify
	}
	return 0
}

func (m *PrePrepare) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *PrePrepare) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

// Prepare 准备阶段
type Prepare struct {
	View                 uint64   `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	Sequence             int64    `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Digest               string   `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	Identify             uint64   `protobuf:"varint,4,opt,name=identify,proto3" json:"identify,omitempty"`
	Signature            []byte   `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	ChannelId            string   `protobuf:"bytes,6,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Prepare) Reset()         { *m = Prepare{} }
func (m *Prepare) String() string { return proto.CompactTextString(m) }
func (*Prepare) ProtoMessage()    {}
func (*Prepare) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d2d862f434b808f, []int{7}
}

func (m *Prepare) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Prepare.Unmarshal(m, b)
}
func (m *Prepare) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Prepare.Marshal(b, m, deterministic)
}
func (m *Prepare) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Prepare.Merge(m, src)
}
func (m *Prepare) XXX_Size() int {
	return xxx_messageInfo_Prepare.Size(m)
}
func (m *Prepare) XXX_DiscardUnknown() {
	xxx_messageInfo_Prepare.DiscardUnknown(m)
}

var xxx_messageInfo_Prepare proto.InternalMessageInfo

func (m *Prepare) GetView() uint64 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *Prepare) GetSequence() int64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *Prepare) GetDigest() string {
	if m != nil {
		return m.Digest
	}
	return ""
}

func (m *Prepare) GetIdentify() uint64 {
	if m != nil {
		return m.Identify
	}
	return 0
}

func (m *Prepare) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *Prepare) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

type Commit struct {
	View                 uint64   `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	Sequence             int64    `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Digest               string   `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	Identify             uint64   `protobuf:"varint,4,opt,name=identify,proto3" json:"identify,omitempty"`
	Signature            []byte   `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	ChannelId            string   `protobuf:"bytes,6,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Commit) Reset()         { *m = Commit{} }
func (m *Commit) String() string { return proto.CompactTextString(m) }
func (*Commit) ProtoMessage()    {}
func (*Commit) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d2d862f434b808f, []int{8}
}

func (m *Commit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Commit.Unmarshal(m, b)
}
func (m *Commit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Commit.Marshal(b, m, deterministic)
}
func (m *Commit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Commit.Merge(m, src)
}
func (m *Commit) XXX_Size() int {
	return xxx_messageInfo_Commit.Size(m)
}
func (m *Commit) XXX_DiscardUnknown() {
	xxx_messageInfo_Commit.DiscardUnknown(m)
}

var xxx_messageInfo_Commit proto.InternalMessageInfo

func (m *Commit) GetView() uint64 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *Commit) GetSequence() int64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *Commit) GetDigest() string {
	if m != nil {
		return m.Digest
	}
	return ""
}

func (m *Commit) GetIdentify() uint64 {
	if m != nil {
		return m.Identify
	}
	return 0
}

func (m *Commit) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *Commit) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

type Reply struct {
	View                 uint64   `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	TimeStamp            uint64   `protobuf:"varint,2,opt,name=time_stamp,json=timeStamp,proto3" json:"time_stamp,omitempty"`
	Id                   uint64   `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Result               *Result  `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Reply) Reset()         { *m = Reply{} }
func (m *Reply) String() string { return proto.CompactTextString(m) }
func (*Reply) ProtoMessage()    {}
func (*Reply) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d2d862f434b808f, []int{9}
}

func (m *Reply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reply.Unmarshal(m, b)
}
func (m *Reply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reply.Marshal(b, m, deterministic)
}
func (m *Reply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reply.Merge(m, src)
}
func (m *Reply) XXX_Size() int {
	return xxx_messageInfo_Reply.Size(m)
}
func (m *Reply) XXX_DiscardUnknown() {
	xxx_messageInfo_Reply.DiscardUnknown(m)
}

var xxx_messageInfo_Reply proto.InternalMessageInfo

func (m *Reply) GetView() uint64 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *Reply) GetTimeStamp() uint64 {
	if m != nil {
		return m.TimeStamp
	}
	return 0
}

func (m *Reply) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Reply) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

type CheckPoint struct {
	Sequence             int64    `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Digest               string   `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	Id                   uint64   `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	ChannelId            string   `protobuf:"bytes,4,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckPoint) Reset()         { *m = CheckPoint{} }
func (m *CheckPoint) String() string { return proto.CompactTextString(m) }
func (*CheckPoint) ProtoMessage()    {}
func (*CheckPoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d2d862f434b808f, []int{10}
}

func (m *CheckPoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckPoint.Unmarshal(m, b)
}
func (m *CheckPoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckPoint.Marshal(b, m, deterministic)
}
func (m *CheckPoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckPoint.Merge(m, src)
}
func (m *CheckPoint) XXX_Size() int {
	return xxx_messageInfo_CheckPoint.Size(m)
}
func (m *CheckPoint) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckPoint.DiscardUnknown(m)
}

var xxx_messageInfo_CheckPoint proto.InternalMessageInfo

func (m *CheckPoint) GetSequence() int64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *CheckPoint) GetDigest() string {
	if m != nil {
		return m.Digest
	}
	return ""
}

func (m *CheckPoint) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CheckPoint) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

type ViewChangeC struct {
	Sequence             int64    `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Id                   uint64   `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ViewChangeC) Reset()         { *m = ViewChangeC{} }
func (m *ViewChangeC) String() string { return proto.CompactTextString(m) }
func (*ViewChangeC) ProtoMessage()    {}
func (*ViewChangeC) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d2d862f434b808f, []int{11}
}

func (m *ViewChangeC) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ViewChangeC.Unmarshal(m, b)
}
func (m *ViewChangeC) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ViewChangeC.Marshal(b, m, deterministic)
}
func (m *ViewChangeC) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViewChangeC.Merge(m, src)
}
func (m *ViewChangeC) XXX_Size() int {
	return xxx_messageInfo_ViewChangeC.Size(m)
}
func (m *ViewChangeC) XXX_DiscardUnknown() {
	xxx_messageInfo_ViewChangeC.DiscardUnknown(m)
}

var xxx_messageInfo_ViewChangeC proto.InternalMessageInfo

func (m *ViewChangeC) GetSequence() int64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *ViewChangeC) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ViewChangePq struct {
	Sequence             int64    `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Digest               string   `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	View                 uint64   `protobuf:"varint,3,opt,name=view,proto3" json:"view,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ViewChangePq) Reset()         { *m = ViewChangePq{} }
func (m *ViewChangePq) String() string { return proto.CompactTextString(m) }
func (*ViewChangePq) ProtoMessage()    {}
func (*ViewChangePq) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d2d862f434b808f, []int{12}
}

func (m *ViewChangePq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ViewChangePq.Unmarshal(m, b)
}
func (m *ViewChangePq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ViewChangePq.Marshal(b, m, deterministic)
}
func (m *ViewChangePq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViewChangePq.Merge(m, src)
}
func (m *ViewChangePq) XXX_Size() int {
	return xxx_messageInfo_ViewChangePq.Size(m)
}
func (m *ViewChangePq) XXX_DiscardUnknown() {
	xxx_messageInfo_ViewChangePq.DiscardUnknown(m)
}

var xxx_messageInfo_ViewChangePq proto.InternalMessageInfo

func (m *ViewChangePq) GetSequence() int64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *ViewChangePq) GetDigest() string {
	if m != nil {
		return m.Digest
	}
	return ""
}

func (m *ViewChangePq) GetView() uint64 {
	if m != nil {
		return m.View
	}
	return 0
}

type PQSet struct {
	Set                  []*ViewChangePq `protobuf:"bytes,1,rep,name=set,proto3" json:"set,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PQSet) Reset()         { *m = PQSet{} }
func (m *PQSet) String() string { return proto.CompactTextString(m) }
func (*PQSet) ProtoMessage()    {}
func (*PQSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d2d862f434b808f, []int{13}
}

func (m *PQSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PQSet.Unmarshal(m, b)
}
func (m *PQSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PQSet.Marshal(b, m, deterministic)
}
func (m *PQSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PQSet.Merge(m, src)
}
func (m *PQSet) XXX_Size() int {
	return xxx_messageInfo_PQSet.Size(m)
}
func (m *PQSet) XXX_DiscardUnknown() {
	xxx_messageInfo_PQSet.DiscardUnknown(m)
}

var xxx_messageInfo_PQSet proto.InternalMessageInfo

func (m *PQSet) GetSet() []*ViewChangePq {
	if m != nil {
		return m.Set
	}
	return nil
}

type ViewChange struct {
	View                 uint64          `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	H                    uint64          `protobuf:"varint,2,opt,name=h,proto3" json:"h,omitempty"`
	CSet                 []*ViewChangeC  `protobuf:"bytes,3,rep,name=c_set,json=cSet,proto3" json:"c_set,omitempty"`
	PSet                 []*ViewChangePq `protobuf:"bytes,4,rep,name=p_set,json=pSet,proto3" json:"p_set,omitempty"`
	QSet                 []*ViewChangePq `protobuf:"bytes,5,rep,name=q_set,json=qSet,proto3" json:"q_set,omitempty"`
	Id                   uint64          `protobuf:"varint,6,opt,name=id,proto3" json:"id,omitempty"`
	Signature            []byte          `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ViewChange) Reset()         { *m = ViewChange{} }
func (m *ViewChange) String() string { return proto.CompactTextString(m) }
func (*ViewChange) ProtoMessage()    {}
func (*ViewChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d2d862f434b808f, []int{14}
}

func (m *ViewChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ViewChange.Unmarshal(m, b)
}
func (m *ViewChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ViewChange.Marshal(b, m, deterministic)
}
func (m *ViewChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViewChange.Merge(m, src)
}
func (m *ViewChange) XXX_Size() int {
	return xxx_messageInfo_ViewChange.Size(m)
}
func (m *ViewChange) XXX_DiscardUnknown() {
	xxx_messageInfo_ViewChange.DiscardUnknown(m)
}

var xxx_messageInfo_ViewChange proto.InternalMessageInfo

func (m *ViewChange) GetView() uint64 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *ViewChange) GetH() uint64 {
	if m != nil {
		return m.H
	}
	return 0
}

func (m *ViewChange) GetCSet() []*ViewChangeC {
	if m != nil {
		return m.CSet
	}
	return nil
}

func (m *ViewChange) GetPSet() []*ViewChangePq {
	if m != nil {
		return m.PSet
	}
	return nil
}

func (m *ViewChange) GetQSet() []*ViewChangePq {
	if m != nil {
		return m.QSet
	}
	return nil
}

func (m *ViewChange) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ViewChange) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type NewView struct {
	View                 uint64            `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	VSet                 []*ViewChange     `protobuf:"bytes,2,rep,name=v_set,json=vSet,proto3" json:"v_set,omitempty"`
	XSet                 map[uint64]string `protobuf:"bytes,3,rep,name=x_set,json=xSet,proto3" json:"x_set,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Id                   uint64            `protobuf:"varint,4,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *NewView) Reset()         { *m = NewView{} }
func (m *NewView) String() string { return proto.CompactTextString(m) }
func (*NewView) ProtoMessage()    {}
func (*NewView) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d2d862f434b808f, []int{15}
}

func (m *NewView) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewView.Unmarshal(m, b)
}
func (m *NewView) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewView.Marshal(b, m, deterministic)
}
func (m *NewView) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewView.Merge(m, src)
}
func (m *NewView) XXX_Size() int {
	return xxx_messageInfo_NewView.Size(m)
}
func (m *NewView) XXX_DiscardUnknown() {
	xxx_messageInfo_NewView.DiscardUnknown(m)
}

var xxx_messageInfo_NewView proto.InternalMessageInfo

func (m *NewView) GetView() uint64 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *NewView) GetVSet() []*ViewChange {
	if m != nil {
		return m.VSet
	}
	return nil
}

func (m *NewView) GetXSet() map[uint64]string {
	if m != nil {
		return m.XSet
	}
	return nil
}

func (m *NewView) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// Response returns a success
// or failure status to the sender.
type Response struct {
	Channel string `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	// Status code, which may be used to programatically respond to success/failure.
	Status common.Status `protobuf:"varint,2,opt,name=status,proto3,enum=common.Status" json:"status,omitempty"`
	// Info string which may contain additional information about the returned status.
	Info                 string   `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d2d862f434b808f, []int{16}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *Response) GetStatus() common.Status {
	if m != nil {
		return m.Status
	}
	return common.Status_UNKNOWN
}

func (m *Response) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

func init() {
	proto.RegisterEnum("pbft.TxType", TxType_name, TxType_value)
	proto.RegisterType((*StepRequest)(nil), "pbft.StepRequest")
	proto.RegisterType((*StepResponse)(nil), "pbft.StepResponse")
	proto.RegisterType((*Operation)(nil), "pbft.Operation")
	proto.RegisterType((*Result)(nil), "pbft.Result")
	proto.RegisterType((*Request)(nil), "pbft.Request")
	proto.RegisterType((*Message)(nil), "pbft.Message")
	proto.RegisterType((*PrePrepare)(nil), "pbft.PrePrepare")
	proto.RegisterType((*Prepare)(nil), "pbft.Prepare")
	proto.RegisterType((*Commit)(nil), "pbft.Commit")
	proto.RegisterType((*Reply)(nil), "pbft.Reply")
	proto.RegisterType((*CheckPoint)(nil), "pbft.CheckPoint")
	proto.RegisterType((*ViewChangeC)(nil), "pbft.ViewChangeC")
	proto.RegisterType((*ViewChangePq)(nil), "pbft.ViewChangePq")
	proto.RegisterType((*PQSet)(nil), "pbft.PQSet")
	proto.RegisterType((*ViewChange)(nil), "pbft.ViewChange")
	proto.RegisterType((*NewView)(nil), "pbft.NewView")
	proto.RegisterMapType((map[uint64]string)(nil), "pbft.NewView.XSetEntry")
	proto.RegisterType((*Response)(nil), "pbft.Response")
}

func init() { proto.RegisterFile("orderer/pbft/cluster.proto", fileDescriptor_1d2d862f434b808f) }

var fileDescriptor_1d2d862f434b808f = []byte{
	// 950 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0xeb, 0x8e, 0xdb, 0x44,
	0x14, 0x8e, 0x1d, 0x5f, 0xe2, 0xb3, 0x69, 0x9a, 0x0e, 0x08, 0xaa, 0x08, 0x04, 0xb2, 0x4a, 0x5b,
	0xaa, 0x6e, 0x42, 0x97, 0x22, 0x0a, 0xe2, 0x4f, 0x1b, 0x2d, 0x6c, 0xa5, 0x76, 0x37, 0x4c, 0x56,
	0x15, 0xf0, 0x27, 0x38, 0xc9, 0x49, 0x62, 0x35, 0xb1, 0x27, 0xf6, 0x24, 0xbb, 0x79, 0x06, 0x9e,
	0x04, 0x5e, 0x81, 0x27, 0xe0, 0x05, 0x78, 0x1e, 0x34, 0x17, 0x5f, 0x62, 0x76, 0x57, 0x02, 0xf1,
	0x03, 0x29, 0x52, 0x66, 0xce, 0x39, 0xdf, 0x39, 0xdf, 0xf9, 0xe6, 0xe2, 0x81, 0x4e, 0x9c, 0x4c,
	0x31, 0xc1, 0xa4, 0xc7, 0xc6, 0x33, 0xde, 0x9b, 0x2c, 0x37, 0x29, 0xc7, 0xa4, 0xcb, 0x92, 0x98,
	0xc7, 0xc4, 0x12, 0xb6, 0xce, 0x3b, 0x93, 0x78, 0xb5, 0x8a, 0xa3, 0x9e, 0xfa, 0x53, 0x2e, 0xff,
	0x0f, 0x13, 0x0e, 0x86, 0x1c, 0x19, 0xc5, 0xf5, 0x06, 0x53, 0x4e, 0x9e, 0xc1, 0xed, 0x44, 0x0d,
	0x47, 0xfa, 0xff, 0xae, 0xf1, 0xb1, 0xf1, 0xf0, 0xe0, 0xe8, 0x56, 0x57, 0x24, 0xe9, 0xea, 0xb8,
	0x93, 0x1a, 0x6d, 0x69, 0x7f, 0x86, 0x7c, 0x0e, 0x84, 0x25, 0x28, 0x7e, 0x41, 0x82, 0x39, 0xd8,
	0x94, 0xe0, 0xb6, 0x02, 0x0f, 0x12, 0x1c, 0x28, 0xff, 0x49, 0x8d, 0xde, 0x29, 0xa2, 0x4b, 0xc5,
	0xab, 0xf8, 0x7a, 0xb9, 0x78, 0x01, 0x6e, 0x55, 0x90, 0x5f, 0x40, 0x4b, 0xb4, 0x15, 0x16, 0xac,
	0x2d, 0x09, 0x6c, 0x2a, 0x60, 0x5f, 0xfa, 0x4e, 0x6a, 0xf4, 0x96, 0x8a, 0x2a, 0x71, 0x9e, 0x2c,
	0x70, 0xf2, 0x96, 0xc5, 0x61, 0x54, 0x40, 0xed, 0x32, 0xe7, 0xbe, 0xf0, 0x0f, 0x84, 0x5f, 0x70,
	0x2e, 0xa2, 0x75, 0x8a, 0x17, 0x1e, 0xb8, 0x2c, 0xd8, 0x2d, 0xe3, 0x60, 0xea, 0xbf, 0x82, 0xa6,
	0x92, 0x32, 0x65, 0x71, 0x94, 0x22, 0x79, 0x02, 0x07, 0x85, 0x96, 0xa9, 0xd6, 0xb1, 0x95, 0xe9,
	0xa8, 0x82, 0x4e, 0x6a, 0x14, 0x72, 0x21, 0xd3, 0x72, 0xb6, 0x5f, 0x0c, 0xf0, 0xce, 0x18, 0x26,
	0x01, 0x0f, 0xe3, 0x88, 0x3c, 0x86, 0x06, 0x46, 0x5b, 0x5c, 0xc6, 0x0c, 0x75, 0xa2, 0x76, 0x57,
	0x2f, 0xe4, 0xb1, 0xb6, 0xd3, 0x3c, 0x82, 0x7c, 0x08, 0x30, 0x59, 0x04, 0x51, 0x84, 0xcb, 0x51,
	0x38, 0x95, 0x6b, 0xe0, 0x51, 0x4f, 0x5b, 0x5e, 0x4e, 0xa5, 0x3b, 0x8e, 0x66, 0xe1, 0x7c, 0x94,
	0xe2, 0x5a, 0x4a, 0x6c, 0x51, 0x4f, 0x59, 0x86, 0xb8, 0x26, 0x04, 0x2c, 0xbe, 0x63, 0x28, 0x25,
	0xf4, 0xa8, 0x1c, 0xfb, 0x0d, 0x70, 0x28, 0xa6, 0x9b, 0x25, 0xf7, 0x2f, 0xc0, 0xcd, 0xe4, 0xfb,
	0x08, 0xcc, 0x98, 0x69, 0x3a, 0xb7, 0x55, 0x5f, 0x39, 0x63, 0x6a, 0xc6, 0x4c, 0x14, 0xe2, 0xe1,
	0x0a, 0x47, 0x29, 0x0f, 0x56, 0x4c, 0xf2, 0xb0, 0xa8, 0x27, 0x2c, 0x43, 0x61, 0x20, 0x2d, 0x30,
	0xc3, 0xa9, 0xae, 0x6f, 0x86, 0x53, 0xf2, 0x01, 0x78, 0x69, 0x38, 0x8f, 0x02, 0xbe, 0x49, 0x54,
	0xf5, 0x26, 0x2d, 0x0c, 0xfe, 0x53, 0x70, 0x5f, 0x63, 0x9a, 0x06, 0x73, 0x24, 0x9f, 0x42, 0x43,
	0x8b, 0x26, 0x64, 0xad, 0xff, 0x6d, 0x7b, 0xd2, 0xdc, 0xed, 0xff, 0x69, 0x00, 0x14, 0xfb, 0x4e,
	0xf4, 0xb6, 0x0d, 0xf1, 0x42, 0x92, 0xb6, 0xa8, 0x1c, 0x93, 0x0e, 0x34, 0x52, 0x11, 0x1e, 0x4d,
	0x50, 0x72, 0xac, 0xd3, 0x7c, 0x4e, 0xde, 0x03, 0x67, 0x1a, 0xce, 0xb3, 0x9d, 0xe8, 0x51, 0x3d,
	0x23, 0x0f, 0xc0, 0x5d, 0x29, 0x32, 0x7a, 0xa7, 0x69, 0x02, 0x9a, 0x21, 0xcd, 0xbc, 0x22, 0x79,
	0x38, 0xc5, 0x88, 0x87, 0xb3, 0x9d, 0xdc, 0x58, 0x16, 0xcd, 0xe7, 0xfb, 0xfd, 0x3a, 0x95, 0x7e,
	0x2b, 0x8b, 0xe8, 0x56, 0x16, 0xd1, 0xff, 0xcd, 0x00, 0xf7, 0xbf, 0xee, 0xaa, 0x4c, 0xd6, 0xba,
	0x89, 0xac, 0x7d, 0x33, 0x59, 0xa7, 0x4a, 0xf6, 0x57, 0x03, 0x1c, 0x75, 0x08, 0xff, 0xff, 0x5c,
	0x19, 0xd8, 0x14, 0xd9, 0x72, 0x77, 0x25, 0xd3, 0x7f, 0xb8, 0xa3, 0xef, 0x81, 0x93, 0xc8, 0x63,
	0xb3, 0x7f, 0x1f, 0xa9, 0xa3, 0x44, 0xb5, 0xcf, 0x8f, 0x01, 0x8a, 0x6b, 0x66, 0x4f, 0x0c, 0xe3,
	0x5a, 0x31, 0xcc, 0x3d, 0x31, 0xaa, 0x75, 0xf7, 0x5b, 0xb4, 0xaa, 0x2d, 0x7e, 0x05, 0x07, 0x6f,
	0x42, 0xbc, 0xe8, 0x2f, 0x82, 0x68, 0x8e, 0xfd, 0x1b, 0x2b, 0xaa, 0xcc, 0x66, 0x96, 0xd9, 0x7f,
	0x03, 0xcd, 0x02, 0x3a, 0x58, 0xff, 0x2b, 0xb6, 0x99, 0xb0, 0xf5, 0x42, 0x58, 0xff, 0x10, 0xec,
	0xc1, 0xf7, 0x43, 0xe4, 0xe4, 0x1e, 0xd4, 0x53, 0xe4, 0xfa, 0x58, 0x13, 0xa5, 0x57, 0xb9, 0x22,
	0x15, 0x6e, 0x79, 0xac, 0x0b, 0xeb, 0x95, 0x4b, 0xd5, 0x04, 0x63, 0xa1, 0x89, 0x1b, 0x0b, 0x72,
	0x1f, 0xec, 0xc9, 0x48, 0x24, 0xae, 0xcb, 0xc4, 0x77, 0xaa, 0x89, 0xfb, 0xd4, 0x9a, 0x88, 0xf2,
	0x0f, 0xc0, 0x66, 0x32, 0xce, 0xba, 0x96, 0x80, 0xc5, 0x74, 0xe0, 0x5a, 0x06, 0xda, 0xd7, 0x07,
	0xae, 0x45, 0xa0, 0x52, 0xd0, 0xb9, 0xfa, 0x96, 0x73, 0xab, 0xb7, 0xdc, 0xef, 0x06, 0xb8, 0xa7,
	0x78, 0x21, 0xf2, 0x5c, 0xd9, 0xd5, 0x27, 0x60, 0x6f, 0x65, 0x59, 0x53, 0x96, 0x6d, 0x57, 0xcb,
	0x52, 0x6b, 0x2b, 0x8a, 0x3e, 0x06, 0xfb, 0xb2, 0xd4, 0xee, 0xfb, 0x2a, 0x4c, 0x27, 0xee, 0xfe,
	0x30, 0x44, 0x7e, 0x1c, 0xf1, 0x64, 0x47, 0xad, 0xcb, 0x82, 0xa2, 0x95, 0x51, 0xec, 0x7c, 0x09,
	0x5e, 0x1e, 0x42, 0xda, 0x50, 0x7f, 0x8b, 0x3b, 0x4d, 0x42, 0x0c, 0xc9, 0xbb, 0x60, 0x6f, 0x83,
	0xe5, 0x06, 0xf5, 0xb2, 0xaa, 0xc9, 0xd7, 0xe6, 0x33, 0xc3, 0xff, 0x19, 0x1a, 0xf9, 0xe7, 0xef,
	0x2e, 0xb8, 0x7a, 0xc7, 0x49, 0xac, 0x47, 0xb3, 0x29, 0xb9, 0x0f, 0x4e, 0xca, 0x03, 0xbe, 0x49,
	0x65, 0x82, 0xd6, 0x51, 0x2b, 0xfb, 0x94, 0x0d, 0xa5, 0x95, 0x6a, 0xaf, 0xe8, 0x3f, 0x8c, 0x66,
	0xb1, 0x3e, 0xf8, 0x72, 0xfc, 0xe8, 0x21, 0x38, 0xe7, 0x97, 0xe7, 0x3b, 0x26, 0x76, 0x26, 0x9c,
	0xff, 0x38, 0x38, 0x3e, 0x3d, 0xa3, 0xaf, 0x9f, 0xbf, 0x6a, 0xd7, 0xb2, 0x79, 0xff, 0xec, 0xf4,
	0xdb, 0x97, 0xdf, 0xb5, 0x8d, 0xa3, 0x6f, 0xc0, 0xed, 0xab, 0x67, 0x10, 0x79, 0x02, 0x96, 0xf8,
	0x32, 0x13, 0xbd, 0xea, 0xa5, 0x07, 0x4f, 0x87, 0x94, 0x4d, 0x8a, 0xf9, 0x43, 0xe3, 0x33, 0xe3,
	0xc5, 0x18, 0x1e, 0xc5, 0xc9, 0xbc, 0xbb, 0xd8, 0x31, 0x4c, 0x96, 0x38, 0x9d, 0x63, 0xd2, 0x9d,
	0x05, 0xe3, 0x24, 0x9c, 0xa8, 0x87, 0x53, 0xda, 0xd5, 0xef, 0x2d, 0x09, 0xff, 0xe9, 0xe9, 0x3c,
	0xe4, 0x8b, 0xcd, 0x58, 0xf4, 0xd1, 0x2b, 0x41, 0x7a, 0x0a, 0x72, 0xa8, 0x20, 0x87, 0xf3, 0xb8,
	0x57, 0x7e, 0xa5, 0x8d, 0x1d, 0x69, 0xff, 0xfc, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x3e, 0x92,
	0x31, 0x5a, 0xbc, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ClusterClient is the client API for Cluster service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ClusterClient interface {
	// Step passes an implementation-specific message to another cluster member.
	Step(ctx context.Context, opts ...grpc.CallOption) (Cluster_StepClient, error)
}

type clusterClient struct {
	cc *grpc.ClientConn
}

func NewClusterClient(cc *grpc.ClientConn) ClusterClient {
	return &clusterClient{cc}
}

func (c *clusterClient) Step(ctx context.Context, opts ...grpc.CallOption) (Cluster_StepClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Cluster_serviceDesc.Streams[0], "/pbft.Cluster/Step", opts...)
	if err != nil {
		return nil, err
	}
	x := &clusterStepClient{stream}
	return x, nil
}

type Cluster_StepClient interface {
	Send(*StepRequest) error
	Recv() (*StepResponse, error)
	grpc.ClientStream
}

type clusterStepClient struct {
	grpc.ClientStream
}

func (x *clusterStepClient) Send(m *StepRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *clusterStepClient) Recv() (*StepResponse, error) {
	m := new(StepResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ClusterServer is the server API for Cluster service.
type ClusterServer interface {
	// Step passes an implementation-specific message to another cluster member.
	Step(Cluster_StepServer) error
}

// UnimplementedClusterServer can be embedded to have forward compatible implementations.
type UnimplementedClusterServer struct {
}

func (*UnimplementedClusterServer) Step(srv Cluster_StepServer) error {
	return status.Errorf(codes.Unimplemented, "method Step not implemented")
}

func RegisterClusterServer(s *grpc.Server, srv ClusterServer) {
	s.RegisterService(&_Cluster_serviceDesc, srv)
}

func _Cluster_Step_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ClusterServer).Step(&clusterStepServer{stream})
}

type Cluster_StepServer interface {
	Send(*StepResponse) error
	Recv() (*StepRequest, error)
	grpc.ServerStream
}

type clusterStepServer struct {
	grpc.ServerStream
}

func (x *clusterStepServer) Send(m *StepResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *clusterStepServer) Recv() (*StepRequest, error) {
	m := new(StepRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Cluster_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pbft.Cluster",
	HandlerType: (*ClusterServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Step",
			Handler:       _Cluster_Step_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "orderer/pbft/cluster.proto",
}
