// Code generated by protoc-gen-go. DO NOT EDIT.
// source: orderer/pbft/metadata.proto

package pbft

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// BlockMetadata stores data used by the pbft OSNs when
// coordinating with each other, to be serialized into
// block meta dta field and used after failres and restarts.
type BlockMetadata struct {
	// Maintains a mapping between the cluster's OSNs
	// and their Raft IDs.
	ConsenterIds []uint64 `protobuf:"varint,1,rep,packed,name=consenter_ids,json=consenterIds,proto3" json:"consenter_ids,omitempty"`
	// Carries the pbft ID value that will be assigned
	// to the next OSN that will join this cluster.
	NextConsenterId uint64 `protobuf:"varint,2,opt,name=next_consenter_id,json=nextConsenterId,proto3" json:"next_consenter_id,omitempty"`
	// view of pbft entry for current block.
	PbftView             uint64   `protobuf:"varint,3,opt,name=pbft_view,json=pbftView,proto3" json:"pbft_view,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockMetadata) Reset()         { *m = BlockMetadata{} }
func (m *BlockMetadata) String() string { return proto.CompactTextString(m) }
func (*BlockMetadata) ProtoMessage()    {}
func (*BlockMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb9b02584c2f8dca, []int{0}
}

func (m *BlockMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockMetadata.Unmarshal(m, b)
}
func (m *BlockMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockMetadata.Marshal(b, m, deterministic)
}
func (m *BlockMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockMetadata.Merge(m, src)
}
func (m *BlockMetadata) XXX_Size() int {
	return xxx_messageInfo_BlockMetadata.Size(m)
}
func (m *BlockMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_BlockMetadata proto.InternalMessageInfo

func (m *BlockMetadata) GetConsenterIds() []uint64 {
	if m != nil {
		return m.ConsenterIds
	}
	return nil
}

func (m *BlockMetadata) GetNextConsenterId() uint64 {
	if m != nil {
		return m.NextConsenterId
	}
	return 0
}

func (m *BlockMetadata) GetPbftView() uint64 {
	if m != nil {
		return m.PbftView
	}
	return 0
}

// ClusterMetadata encapsulates metadata that is exchanged among cluster nodes
type ClusterMetadata struct {
	// Indicates active nodes in cluster that are reacheable by pbft leader
	ActiveNodes          []uint64 `protobuf:"varint,1,rep,packed,name=active_nodes,json=activeNodes,proto3" json:"active_nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClusterMetadata) Reset()         { *m = ClusterMetadata{} }
func (m *ClusterMetadata) String() string { return proto.CompactTextString(m) }
func (*ClusterMetadata) ProtoMessage()    {}
func (*ClusterMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb9b02584c2f8dca, []int{1}
}

func (m *ClusterMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterMetadata.Unmarshal(m, b)
}
func (m *ClusterMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterMetadata.Marshal(b, m, deterministic)
}
func (m *ClusterMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterMetadata.Merge(m, src)
}
func (m *ClusterMetadata) XXX_Size() int {
	return xxx_messageInfo_ClusterMetadata.Size(m)
}
func (m *ClusterMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterMetadata proto.InternalMessageInfo

func (m *ClusterMetadata) GetActiveNodes() []uint64 {
	if m != nil {
		return m.ActiveNodes
	}
	return nil
}

func init() {
	proto.RegisterType((*BlockMetadata)(nil), "pbft.BlockMetadata")
	proto.RegisterType((*ClusterMetadata)(nil), "pbft.ClusterMetadata")
}

func init() { proto.RegisterFile("orderer/pbft/metadata.proto", fileDescriptor_fb9b02584c2f8dca) }

var fileDescriptor_fb9b02584c2f8dca = []byte{
	// 241 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x3f, 0x4f, 0x02, 0x41,
	0x10, 0xc5, 0x83, 0x5c, 0x8c, 0xae, 0x10, 0xe2, 0x55, 0x97, 0xd0, 0x20, 0x36, 0x84, 0x84, 0xdd,
	0x42, 0x3e, 0x01, 0x54, 0x16, 0x5a, 0x50, 0x58, 0xd8, 0x5c, 0xf6, 0xcf, 0x70, 0x6c, 0x3c, 0x6e,
	0x2e, 0xb3, 0x03, 0x68, 0xe1, 0x77, 0x37, 0xcb, 0xe1, 0x71, 0xed, 0xef, 0xbd, 0x97, 0x37, 0x6f,
	0xc4, 0x18, 0xc9, 0x01, 0x01, 0xa9, 0xda, 0x6c, 0x59, 0xed, 0x81, 0xb5, 0xd3, 0xac, 0x65, 0x4d,
	0xc8, 0x98, 0x26, 0x11, 0x4e, 0x7f, 0xc5, 0x70, 0x55, 0xa2, 0xfd, 0x7a, 0xbb, 0x88, 0xe9, 0xb3,
	0x18, 0x5a, 0xac, 0x02, 0x54, 0x0c, 0x94, 0x7b, 0x17, 0xb2, 0xde, 0xa4, 0x3f, 0x4b, 0x36, 0x83,
	0x16, 0xbe, 0xba, 0x90, 0xce, 0xc5, 0x63, 0x05, 0xdf, 0x9c, 0x77, 0x9d, 0xd9, 0xcd, 0xa4, 0x37,
	0x4b, 0x36, 0xa3, 0x28, 0xac, 0xaf, 0xe6, 0x74, 0x2c, 0xee, 0x63, 0x53, 0x7e, 0xf4, 0x70, 0xca,
	0xfa, 0x67, 0xcf, 0x5d, 0x04, 0x1f, 0x1e, 0x4e, 0xd3, 0xa5, 0x18, 0xad, 0xcb, 0x43, 0x60, 0xa0,
	0xf6, 0x80, 0x27, 0x31, 0xd0, 0x96, 0xfd, 0x11, 0xf2, 0x0a, 0x1d, 0xfc, 0xf7, 0x3f, 0x34, 0xec,
	0x3d, 0xa2, 0x95, 0x11, 0x73, 0xa4, 0x42, 0xee, 0x7e, 0x6a, 0xa0, 0x12, 0x5c, 0x01, 0x24, 0xb7,
	0xda, 0x90, 0xb7, 0xcd, 0xb4, 0x20, 0x2f, 0xbb, 0x65, 0xec, 0xf9, 0x5c, 0x16, 0x9e, 0x77, 0x07,
	0x23, 0x2d, 0xee, 0x55, 0x27, 0xa2, 0x9a, 0xc8, 0xa2, 0x89, 0x2c, 0x0a, 0x54, 0xdd, 0x6f, 0x99,
	0xdb, 0x33, 0x7f, 0xf9, 0x0b, 0x00, 0x00, 0xff, 0xff, 0xc5, 0xe8, 0x01, 0x53, 0x44, 0x01, 0x00,
	0x00,
}
